
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Accounting` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Accounting
 * 
 */
export type AccountingModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountingPayload>

export type AggregateAccounting = {
  _count: AccountingCountAggregateOutputType | null
  _avg: AccountingAvgAggregateOutputType | null
  _sum: AccountingSumAggregateOutputType | null
  _min: AccountingMinAggregateOutputType | null
  _max: AccountingMaxAggregateOutputType | null
}

export type AccountingAvgAggregateOutputType = {
  balance: runtime.Decimal | null
}

export type AccountingSumAggregateOutputType = {
  balance: runtime.Decimal | null
}

export type AccountingMinAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  type: $Enums.AccountType | null
  parentId: string | null
  isActive: boolean | null
  balance: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountingMaxAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  type: $Enums.AccountType | null
  parentId: string | null
  isActive: boolean | null
  balance: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountingCountAggregateOutputType = {
  id: number
  code: number
  name: number
  type: number
  parentId: number
  isActive: number
  balance: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccountingAvgAggregateInputType = {
  balance?: true
}

export type AccountingSumAggregateInputType = {
  balance?: true
}

export type AccountingMinAggregateInputType = {
  id?: true
  code?: true
  name?: true
  type?: true
  parentId?: true
  isActive?: true
  balance?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountingMaxAggregateInputType = {
  id?: true
  code?: true
  name?: true
  type?: true
  parentId?: true
  isActive?: true
  balance?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountingCountAggregateInputType = {
  id?: true
  code?: true
  name?: true
  type?: true
  parentId?: true
  isActive?: true
  balance?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccountingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Accounting to aggregate.
   */
  where?: Prisma.AccountingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accountings to fetch.
   */
  orderBy?: Prisma.AccountingOrderByWithRelationInput | Prisma.AccountingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accountings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accountings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Accountings
  **/
  _count?: true | AccountingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountingMaxAggregateInputType
}

export type GetAccountingAggregateType<T extends AccountingAggregateArgs> = {
      [P in keyof T & keyof AggregateAccounting]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccounting[P]>
    : Prisma.GetScalarType<T[P], AggregateAccounting[P]>
}




export type AccountingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountingWhereInput
  orderBy?: Prisma.AccountingOrderByWithAggregationInput | Prisma.AccountingOrderByWithAggregationInput[]
  by: Prisma.AccountingScalarFieldEnum[] | Prisma.AccountingScalarFieldEnum
  having?: Prisma.AccountingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountingCountAggregateInputType | true
  _avg?: AccountingAvgAggregateInputType
  _sum?: AccountingSumAggregateInputType
  _min?: AccountingMinAggregateInputType
  _max?: AccountingMaxAggregateInputType
}

export type AccountingGroupByOutputType = {
  id: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId: string | null
  isActive: boolean
  balance: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: AccountingCountAggregateOutputType | null
  _avg: AccountingAvgAggregateOutputType | null
  _sum: AccountingSumAggregateOutputType | null
  _min: AccountingMinAggregateOutputType | null
  _max: AccountingMaxAggregateOutputType | null
}

export type GetAccountingGroupByPayload<T extends AccountingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountingGroupByOutputType[P]>
      }
    >
  >



export type AccountingWhereInput = {
  AND?: Prisma.AccountingWhereInput | Prisma.AccountingWhereInput[]
  OR?: Prisma.AccountingWhereInput[]
  NOT?: Prisma.AccountingWhereInput | Prisma.AccountingWhereInput[]
  id?: Prisma.StringFilter<"Accounting"> | string
  code?: Prisma.StringFilter<"Accounting"> | string
  name?: Prisma.StringFilter<"Accounting"> | string
  type?: Prisma.EnumAccountTypeFilter<"Accounting"> | $Enums.AccountType
  parentId?: Prisma.StringNullableFilter<"Accounting"> | string | null
  isActive?: Prisma.BoolFilter<"Accounting"> | boolean
  balance?: Prisma.DecimalFilter<"Accounting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"Accounting"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Accounting"> | Date | string
  parent?: Prisma.XOR<Prisma.AccountingNullableScalarRelationFilter, Prisma.AccountingWhereInput> | null
  children?: Prisma.AccountingListRelationFilter
  lines?: Prisma.JournalLineListRelationFilter
  invoiceLines?: Prisma.InvoiceLineListRelationFilter
  billLines?: Prisma.BillLineListRelationFilter
}

export type AccountingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  parent?: Prisma.AccountingOrderByWithRelationInput
  children?: Prisma.AccountingOrderByRelationAggregateInput
  lines?: Prisma.JournalLineOrderByRelationAggregateInput
  invoiceLines?: Prisma.InvoiceLineOrderByRelationAggregateInput
  billLines?: Prisma.BillLineOrderByRelationAggregateInput
}

export type AccountingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.AccountingWhereInput | Prisma.AccountingWhereInput[]
  OR?: Prisma.AccountingWhereInput[]
  NOT?: Prisma.AccountingWhereInput | Prisma.AccountingWhereInput[]
  name?: Prisma.StringFilter<"Accounting"> | string
  type?: Prisma.EnumAccountTypeFilter<"Accounting"> | $Enums.AccountType
  parentId?: Prisma.StringNullableFilter<"Accounting"> | string | null
  isActive?: Prisma.BoolFilter<"Accounting"> | boolean
  balance?: Prisma.DecimalFilter<"Accounting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"Accounting"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Accounting"> | Date | string
  parent?: Prisma.XOR<Prisma.AccountingNullableScalarRelationFilter, Prisma.AccountingWhereInput> | null
  children?: Prisma.AccountingListRelationFilter
  lines?: Prisma.JournalLineListRelationFilter
  invoiceLines?: Prisma.InvoiceLineListRelationFilter
  billLines?: Prisma.BillLineListRelationFilter
}, "id" | "code">

export type AccountingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccountingCountOrderByAggregateInput
  _avg?: Prisma.AccountingAvgOrderByAggregateInput
  _max?: Prisma.AccountingMaxOrderByAggregateInput
  _min?: Prisma.AccountingMinOrderByAggregateInput
  _sum?: Prisma.AccountingSumOrderByAggregateInput
}

export type AccountingScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountingScalarWhereWithAggregatesInput | Prisma.AccountingScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountingScalarWhereWithAggregatesInput | Prisma.AccountingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Accounting"> | string
  code?: Prisma.StringWithAggregatesFilter<"Accounting"> | string
  name?: Prisma.StringWithAggregatesFilter<"Accounting"> | string
  type?: Prisma.EnumAccountTypeWithAggregatesFilter<"Accounting"> | $Enums.AccountType
  parentId?: Prisma.StringNullableWithAggregatesFilter<"Accounting"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"Accounting"> | boolean
  balance?: Prisma.DecimalWithAggregatesFilter<"Accounting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Accounting"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Accounting"> | Date | string
}

export type AccountingCreateInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.AccountingCreateNestedOneWithoutChildrenInput
  children?: Prisma.AccountingCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineCreateNestedManyWithoutAccountInput
}

export type AccountingUncheckedCreateInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId?: string | null
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.AccountingUncheckedCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineUncheckedCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineUncheckedCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineUncheckedCreateNestedManyWithoutAccountInput
}

export type AccountingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.AccountingUpdateOneWithoutChildrenNestedInput
  children?: Prisma.AccountingUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.AccountingUncheckedUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUncheckedUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUncheckedUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUncheckedUpdateManyWithoutAccountNestedInput
}

export type AccountingCreateManyInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId?: string | null
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountingNullableScalarRelationFilter = {
  is?: Prisma.AccountingWhereInput | null
  isNot?: Prisma.AccountingWhereInput | null
}

export type AccountingListRelationFilter = {
  every?: Prisma.AccountingWhereInput
  some?: Prisma.AccountingWhereInput
  none?: Prisma.AccountingWhereInput
}

export type AccountingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccountingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountingAvgOrderByAggregateInput = {
  balance?: Prisma.SortOrder
}

export type AccountingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountingSumOrderByAggregateInput = {
  balance?: Prisma.SortOrder
}

export type AccountingScalarRelationFilter = {
  is?: Prisma.AccountingWhereInput
  isNot?: Prisma.AccountingWhereInput
}

export type AccountingCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutChildrenInput, Prisma.AccountingUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutChildrenInput
  connect?: Prisma.AccountingWhereUniqueInput
}

export type AccountingCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutParentInput, Prisma.AccountingUncheckedCreateWithoutParentInput> | Prisma.AccountingCreateWithoutParentInput[] | Prisma.AccountingUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutParentInput | Prisma.AccountingCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.AccountingCreateManyParentInputEnvelope
  connect?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
}

export type AccountingUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutParentInput, Prisma.AccountingUncheckedCreateWithoutParentInput> | Prisma.AccountingCreateWithoutParentInput[] | Prisma.AccountingUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutParentInput | Prisma.AccountingCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.AccountingCreateManyParentInputEnvelope
  connect?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
}

export type EnumAccountTypeFieldUpdateOperationsInput = {
  set?: $Enums.AccountType
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type AccountingUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutChildrenInput, Prisma.AccountingUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.AccountingUpsertWithoutChildrenInput
  disconnect?: Prisma.AccountingWhereInput | boolean
  delete?: Prisma.AccountingWhereInput | boolean
  connect?: Prisma.AccountingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountingUpdateToOneWithWhereWithoutChildrenInput, Prisma.AccountingUpdateWithoutChildrenInput>, Prisma.AccountingUncheckedUpdateWithoutChildrenInput>
}

export type AccountingUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutParentInput, Prisma.AccountingUncheckedCreateWithoutParentInput> | Prisma.AccountingCreateWithoutParentInput[] | Prisma.AccountingUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutParentInput | Prisma.AccountingCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.AccountingUpsertWithWhereUniqueWithoutParentInput | Prisma.AccountingUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.AccountingCreateManyParentInputEnvelope
  set?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  disconnect?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  delete?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  connect?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  update?: Prisma.AccountingUpdateWithWhereUniqueWithoutParentInput | Prisma.AccountingUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.AccountingUpdateManyWithWhereWithoutParentInput | Prisma.AccountingUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.AccountingScalarWhereInput | Prisma.AccountingScalarWhereInput[]
}

export type AccountingUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutParentInput, Prisma.AccountingUncheckedCreateWithoutParentInput> | Prisma.AccountingCreateWithoutParentInput[] | Prisma.AccountingUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutParentInput | Prisma.AccountingCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.AccountingUpsertWithWhereUniqueWithoutParentInput | Prisma.AccountingUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.AccountingCreateManyParentInputEnvelope
  set?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  disconnect?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  delete?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  connect?: Prisma.AccountingWhereUniqueInput | Prisma.AccountingWhereUniqueInput[]
  update?: Prisma.AccountingUpdateWithWhereUniqueWithoutParentInput | Prisma.AccountingUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.AccountingUpdateManyWithWhereWithoutParentInput | Prisma.AccountingUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.AccountingScalarWhereInput | Prisma.AccountingScalarWhereInput[]
}

export type AccountingCreateNestedOneWithoutLinesInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutLinesInput, Prisma.AccountingUncheckedCreateWithoutLinesInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutLinesInput
  connect?: Prisma.AccountingWhereUniqueInput
}

export type AccountingUpdateOneRequiredWithoutLinesNestedInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutLinesInput, Prisma.AccountingUncheckedCreateWithoutLinesInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutLinesInput
  upsert?: Prisma.AccountingUpsertWithoutLinesInput
  connect?: Prisma.AccountingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountingUpdateToOneWithWhereWithoutLinesInput, Prisma.AccountingUpdateWithoutLinesInput>, Prisma.AccountingUncheckedUpdateWithoutLinesInput>
}

export type AccountingCreateNestedOneWithoutInvoiceLinesInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutInvoiceLinesInput, Prisma.AccountingUncheckedCreateWithoutInvoiceLinesInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutInvoiceLinesInput
  connect?: Prisma.AccountingWhereUniqueInput
}

export type AccountingUpdateOneRequiredWithoutInvoiceLinesNestedInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutInvoiceLinesInput, Prisma.AccountingUncheckedCreateWithoutInvoiceLinesInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutInvoiceLinesInput
  upsert?: Prisma.AccountingUpsertWithoutInvoiceLinesInput
  connect?: Prisma.AccountingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountingUpdateToOneWithWhereWithoutInvoiceLinesInput, Prisma.AccountingUpdateWithoutInvoiceLinesInput>, Prisma.AccountingUncheckedUpdateWithoutInvoiceLinesInput>
}

export type AccountingCreateNestedOneWithoutBillLinesInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutBillLinesInput, Prisma.AccountingUncheckedCreateWithoutBillLinesInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutBillLinesInput
  connect?: Prisma.AccountingWhereUniqueInput
}

export type AccountingUpdateOneRequiredWithoutBillLinesNestedInput = {
  create?: Prisma.XOR<Prisma.AccountingCreateWithoutBillLinesInput, Prisma.AccountingUncheckedCreateWithoutBillLinesInput>
  connectOrCreate?: Prisma.AccountingCreateOrConnectWithoutBillLinesInput
  upsert?: Prisma.AccountingUpsertWithoutBillLinesInput
  connect?: Prisma.AccountingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccountingUpdateToOneWithWhereWithoutBillLinesInput, Prisma.AccountingUpdateWithoutBillLinesInput>, Prisma.AccountingUncheckedUpdateWithoutBillLinesInput>
}

export type AccountingCreateWithoutChildrenInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.AccountingCreateNestedOneWithoutChildrenInput
  lines?: Prisma.JournalLineCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineCreateNestedManyWithoutAccountInput
}

export type AccountingUncheckedCreateWithoutChildrenInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId?: string | null
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.JournalLineUncheckedCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineUncheckedCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineUncheckedCreateNestedManyWithoutAccountInput
}

export type AccountingCreateOrConnectWithoutChildrenInput = {
  where: Prisma.AccountingWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountingCreateWithoutChildrenInput, Prisma.AccountingUncheckedCreateWithoutChildrenInput>
}

export type AccountingCreateWithoutParentInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.AccountingCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineCreateNestedManyWithoutAccountInput
}

export type AccountingUncheckedCreateWithoutParentInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.AccountingUncheckedCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineUncheckedCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineUncheckedCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineUncheckedCreateNestedManyWithoutAccountInput
}

export type AccountingCreateOrConnectWithoutParentInput = {
  where: Prisma.AccountingWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountingCreateWithoutParentInput, Prisma.AccountingUncheckedCreateWithoutParentInput>
}

export type AccountingCreateManyParentInputEnvelope = {
  data: Prisma.AccountingCreateManyParentInput | Prisma.AccountingCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type AccountingUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.AccountingUpdateWithoutChildrenInput, Prisma.AccountingUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.AccountingCreateWithoutChildrenInput, Prisma.AccountingUncheckedCreateWithoutChildrenInput>
  where?: Prisma.AccountingWhereInput
}

export type AccountingUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.AccountingWhereInput
  data: Prisma.XOR<Prisma.AccountingUpdateWithoutChildrenInput, Prisma.AccountingUncheckedUpdateWithoutChildrenInput>
}

export type AccountingUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.AccountingUpdateOneWithoutChildrenNestedInput
  lines?: Prisma.JournalLineUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.JournalLineUncheckedUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUncheckedUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUncheckedUpdateManyWithoutAccountNestedInput
}

export type AccountingUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.AccountingWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountingUpdateWithoutParentInput, Prisma.AccountingUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.AccountingCreateWithoutParentInput, Prisma.AccountingUncheckedCreateWithoutParentInput>
}

export type AccountingUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.AccountingWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountingUpdateWithoutParentInput, Prisma.AccountingUncheckedUpdateWithoutParentInput>
}

export type AccountingUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.AccountingScalarWhereInput
  data: Prisma.XOR<Prisma.AccountingUpdateManyMutationInput, Prisma.AccountingUncheckedUpdateManyWithoutParentInput>
}

export type AccountingScalarWhereInput = {
  AND?: Prisma.AccountingScalarWhereInput | Prisma.AccountingScalarWhereInput[]
  OR?: Prisma.AccountingScalarWhereInput[]
  NOT?: Prisma.AccountingScalarWhereInput | Prisma.AccountingScalarWhereInput[]
  id?: Prisma.StringFilter<"Accounting"> | string
  code?: Prisma.StringFilter<"Accounting"> | string
  name?: Prisma.StringFilter<"Accounting"> | string
  type?: Prisma.EnumAccountTypeFilter<"Accounting"> | $Enums.AccountType
  parentId?: Prisma.StringNullableFilter<"Accounting"> | string | null
  isActive?: Prisma.BoolFilter<"Accounting"> | boolean
  balance?: Prisma.DecimalFilter<"Accounting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"Accounting"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Accounting"> | Date | string
}

export type AccountingCreateWithoutLinesInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.AccountingCreateNestedOneWithoutChildrenInput
  children?: Prisma.AccountingCreateNestedManyWithoutParentInput
  invoiceLines?: Prisma.InvoiceLineCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineCreateNestedManyWithoutAccountInput
}

export type AccountingUncheckedCreateWithoutLinesInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId?: string | null
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.AccountingUncheckedCreateNestedManyWithoutParentInput
  invoiceLines?: Prisma.InvoiceLineUncheckedCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineUncheckedCreateNestedManyWithoutAccountInput
}

export type AccountingCreateOrConnectWithoutLinesInput = {
  where: Prisma.AccountingWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountingCreateWithoutLinesInput, Prisma.AccountingUncheckedCreateWithoutLinesInput>
}

export type AccountingUpsertWithoutLinesInput = {
  update: Prisma.XOR<Prisma.AccountingUpdateWithoutLinesInput, Prisma.AccountingUncheckedUpdateWithoutLinesInput>
  create: Prisma.XOR<Prisma.AccountingCreateWithoutLinesInput, Prisma.AccountingUncheckedCreateWithoutLinesInput>
  where?: Prisma.AccountingWhereInput
}

export type AccountingUpdateToOneWithWhereWithoutLinesInput = {
  where?: Prisma.AccountingWhereInput
  data: Prisma.XOR<Prisma.AccountingUpdateWithoutLinesInput, Prisma.AccountingUncheckedUpdateWithoutLinesInput>
}

export type AccountingUpdateWithoutLinesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.AccountingUpdateOneWithoutChildrenNestedInput
  children?: Prisma.AccountingUpdateManyWithoutParentNestedInput
  invoiceLines?: Prisma.InvoiceLineUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateWithoutLinesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.AccountingUncheckedUpdateManyWithoutParentNestedInput
  invoiceLines?: Prisma.InvoiceLineUncheckedUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUncheckedUpdateManyWithoutAccountNestedInput
}

export type AccountingCreateWithoutInvoiceLinesInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.AccountingCreateNestedOneWithoutChildrenInput
  children?: Prisma.AccountingCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineCreateNestedManyWithoutAccountInput
}

export type AccountingUncheckedCreateWithoutInvoiceLinesInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId?: string | null
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.AccountingUncheckedCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineUncheckedCreateNestedManyWithoutAccountInput
  billLines?: Prisma.BillLineUncheckedCreateNestedManyWithoutAccountInput
}

export type AccountingCreateOrConnectWithoutInvoiceLinesInput = {
  where: Prisma.AccountingWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountingCreateWithoutInvoiceLinesInput, Prisma.AccountingUncheckedCreateWithoutInvoiceLinesInput>
}

export type AccountingUpsertWithoutInvoiceLinesInput = {
  update: Prisma.XOR<Prisma.AccountingUpdateWithoutInvoiceLinesInput, Prisma.AccountingUncheckedUpdateWithoutInvoiceLinesInput>
  create: Prisma.XOR<Prisma.AccountingCreateWithoutInvoiceLinesInput, Prisma.AccountingUncheckedCreateWithoutInvoiceLinesInput>
  where?: Prisma.AccountingWhereInput
}

export type AccountingUpdateToOneWithWhereWithoutInvoiceLinesInput = {
  where?: Prisma.AccountingWhereInput
  data: Prisma.XOR<Prisma.AccountingUpdateWithoutInvoiceLinesInput, Prisma.AccountingUncheckedUpdateWithoutInvoiceLinesInput>
}

export type AccountingUpdateWithoutInvoiceLinesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.AccountingUpdateOneWithoutChildrenNestedInput
  children?: Prisma.AccountingUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateWithoutInvoiceLinesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.AccountingUncheckedUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUncheckedUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUncheckedUpdateManyWithoutAccountNestedInput
}

export type AccountingCreateWithoutBillLinesInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.AccountingCreateNestedOneWithoutChildrenInput
  children?: Prisma.AccountingCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineCreateNestedManyWithoutAccountInput
}

export type AccountingUncheckedCreateWithoutBillLinesInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  parentId?: string | null
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.AccountingUncheckedCreateNestedManyWithoutParentInput
  lines?: Prisma.JournalLineUncheckedCreateNestedManyWithoutAccountInput
  invoiceLines?: Prisma.InvoiceLineUncheckedCreateNestedManyWithoutAccountInput
}

export type AccountingCreateOrConnectWithoutBillLinesInput = {
  where: Prisma.AccountingWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountingCreateWithoutBillLinesInput, Prisma.AccountingUncheckedCreateWithoutBillLinesInput>
}

export type AccountingUpsertWithoutBillLinesInput = {
  update: Prisma.XOR<Prisma.AccountingUpdateWithoutBillLinesInput, Prisma.AccountingUncheckedUpdateWithoutBillLinesInput>
  create: Prisma.XOR<Prisma.AccountingCreateWithoutBillLinesInput, Prisma.AccountingUncheckedCreateWithoutBillLinesInput>
  where?: Prisma.AccountingWhereInput
}

export type AccountingUpdateToOneWithWhereWithoutBillLinesInput = {
  where?: Prisma.AccountingWhereInput
  data: Prisma.XOR<Prisma.AccountingUpdateWithoutBillLinesInput, Prisma.AccountingUncheckedUpdateWithoutBillLinesInput>
}

export type AccountingUpdateWithoutBillLinesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.AccountingUpdateOneWithoutChildrenNestedInput
  children?: Prisma.AccountingUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateWithoutBillLinesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.AccountingUncheckedUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUncheckedUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUncheckedUpdateManyWithoutAccountNestedInput
}

export type AccountingCreateManyParentInput = {
  id?: string
  code: string
  name: string
  type: $Enums.AccountType
  isActive?: boolean
  balance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountingUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.AccountingUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.AccountingUncheckedUpdateManyWithoutParentNestedInput
  lines?: Prisma.JournalLineUncheckedUpdateManyWithoutAccountNestedInput
  invoiceLines?: Prisma.InvoiceLineUncheckedUpdateManyWithoutAccountNestedInput
  billLines?: Prisma.BillLineUncheckedUpdateManyWithoutAccountNestedInput
}

export type AccountingUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAccountTypeFieldUpdateOperationsInput | $Enums.AccountType
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  balance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AccountingCountOutputType
 */

export type AccountingCountOutputType = {
  children: number
  lines: number
  invoiceLines: number
  billLines: number
}

export type AccountingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  children?: boolean | AccountingCountOutputTypeCountChildrenArgs
  lines?: boolean | AccountingCountOutputTypeCountLinesArgs
  invoiceLines?: boolean | AccountingCountOutputTypeCountInvoiceLinesArgs
  billLines?: boolean | AccountingCountOutputTypeCountBillLinesArgs
}

/**
 * AccountingCountOutputType without action
 */
export type AccountingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountingCountOutputType
   */
  select?: Prisma.AccountingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AccountingCountOutputType without action
 */
export type AccountingCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountingWhereInput
}

/**
 * AccountingCountOutputType without action
 */
export type AccountingCountOutputTypeCountLinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JournalLineWhereInput
}

/**
 * AccountingCountOutputType without action
 */
export type AccountingCountOutputTypeCountInvoiceLinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceLineWhereInput
}

/**
 * AccountingCountOutputType without action
 */
export type AccountingCountOutputTypeCountBillLinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BillLineWhereInput
}


export type AccountingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  type?: boolean
  parentId?: boolean
  isActive?: boolean
  balance?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.Accounting$parentArgs<ExtArgs>
  children?: boolean | Prisma.Accounting$childrenArgs<ExtArgs>
  lines?: boolean | Prisma.Accounting$linesArgs<ExtArgs>
  invoiceLines?: boolean | Prisma.Accounting$invoiceLinesArgs<ExtArgs>
  billLines?: boolean | Prisma.Accounting$billLinesArgs<ExtArgs>
  _count?: boolean | Prisma.AccountingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accounting"]>

export type AccountingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  type?: boolean
  parentId?: boolean
  isActive?: boolean
  balance?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.Accounting$parentArgs<ExtArgs>
}, ExtArgs["result"]["accounting"]>

export type AccountingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  type?: boolean
  parentId?: boolean
  isActive?: boolean
  balance?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.Accounting$parentArgs<ExtArgs>
}, ExtArgs["result"]["accounting"]>

export type AccountingSelectScalar = {
  id?: boolean
  code?: boolean
  name?: boolean
  type?: boolean
  parentId?: boolean
  isActive?: boolean
  balance?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccountingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "name" | "type" | "parentId" | "isActive" | "balance" | "createdAt" | "updatedAt", ExtArgs["result"]["accounting"]>
export type AccountingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.Accounting$parentArgs<ExtArgs>
  children?: boolean | Prisma.Accounting$childrenArgs<ExtArgs>
  lines?: boolean | Prisma.Accounting$linesArgs<ExtArgs>
  invoiceLines?: boolean | Prisma.Accounting$invoiceLinesArgs<ExtArgs>
  billLines?: boolean | Prisma.Accounting$billLinesArgs<ExtArgs>
  _count?: boolean | Prisma.AccountingCountOutputTypeDefaultArgs<ExtArgs>
}
export type AccountingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.Accounting$parentArgs<ExtArgs>
}
export type AccountingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.Accounting$parentArgs<ExtArgs>
}

export type $AccountingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Accounting"
  objects: {
    parent: Prisma.$AccountingPayload<ExtArgs> | null
    children: Prisma.$AccountingPayload<ExtArgs>[]
    lines: Prisma.$JournalLinePayload<ExtArgs>[]
    invoiceLines: Prisma.$InvoiceLinePayload<ExtArgs>[]
    billLines: Prisma.$BillLinePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    name: string
    type: $Enums.AccountType
    parentId: string | null
    isActive: boolean
    balance: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accounting"]>
  composites: {}
}

export type AccountingGetPayload<S extends boolean | null | undefined | AccountingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountingPayload, S>

export type AccountingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountingCountAggregateInputType | true
  }

export interface AccountingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Accounting'], meta: { name: 'Accounting' } }
  /**
   * Find zero or one Accounting that matches the filter.
   * @param {AccountingFindUniqueArgs} args - Arguments to find a Accounting
   * @example
   * // Get one Accounting
   * const accounting = await prisma.accounting.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountingFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Accounting that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountingFindUniqueOrThrowArgs} args - Arguments to find a Accounting
   * @example
   * // Get one Accounting
   * const accounting = await prisma.accounting.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Accounting that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingFindFirstArgs} args - Arguments to find a Accounting
   * @example
   * // Get one Accounting
   * const accounting = await prisma.accounting.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountingFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountingFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Accounting that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingFindFirstOrThrowArgs} args - Arguments to find a Accounting
   * @example
   * // Get one Accounting
   * const accounting = await prisma.accounting.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Accountings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Accountings
   * const accountings = await prisma.accounting.findMany()
   * 
   * // Get first 10 Accountings
   * const accountings = await prisma.accounting.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountingWithIdOnly = await prisma.accounting.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountingFindManyArgs>(args?: Prisma.SelectSubset<T, AccountingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Accounting.
   * @param {AccountingCreateArgs} args - Arguments to create a Accounting.
   * @example
   * // Create one Accounting
   * const Accounting = await prisma.accounting.create({
   *   data: {
   *     // ... data to create a Accounting
   *   }
   * })
   * 
   */
  create<T extends AccountingCreateArgs>(args: Prisma.SelectSubset<T, AccountingCreateArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Accountings.
   * @param {AccountingCreateManyArgs} args - Arguments to create many Accountings.
   * @example
   * // Create many Accountings
   * const accounting = await prisma.accounting.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountingCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Accountings and returns the data saved in the database.
   * @param {AccountingCreateManyAndReturnArgs} args - Arguments to create many Accountings.
   * @example
   * // Create many Accountings
   * const accounting = await prisma.accounting.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Accountings and only return the `id`
   * const accountingWithIdOnly = await prisma.accounting.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Accounting.
   * @param {AccountingDeleteArgs} args - Arguments to delete one Accounting.
   * @example
   * // Delete one Accounting
   * const Accounting = await prisma.accounting.delete({
   *   where: {
   *     // ... filter to delete one Accounting
   *   }
   * })
   * 
   */
  delete<T extends AccountingDeleteArgs>(args: Prisma.SelectSubset<T, AccountingDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Accounting.
   * @param {AccountingUpdateArgs} args - Arguments to update one Accounting.
   * @example
   * // Update one Accounting
   * const accounting = await prisma.accounting.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountingUpdateArgs>(args: Prisma.SelectSubset<T, AccountingUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Accountings.
   * @param {AccountingDeleteManyArgs} args - Arguments to filter Accountings to delete.
   * @example
   * // Delete a few Accountings
   * const { count } = await prisma.accounting.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountingDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Accountings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Accountings
   * const accounting = await prisma.accounting.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountingUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Accountings and returns the data updated in the database.
   * @param {AccountingUpdateManyAndReturnArgs} args - Arguments to update many Accountings.
   * @example
   * // Update many Accountings
   * const accounting = await prisma.accounting.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Accountings and only return the `id`
   * const accountingWithIdOnly = await prisma.accounting.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Accounting.
   * @param {AccountingUpsertArgs} args - Arguments to update or create a Accounting.
   * @example
   * // Update or create a Accounting
   * const accounting = await prisma.accounting.upsert({
   *   create: {
   *     // ... data to create a Accounting
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Accounting we want to update
   *   }
   * })
   */
  upsert<T extends AccountingUpsertArgs>(args: Prisma.SelectSubset<T, AccountingUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Accountings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingCountArgs} args - Arguments to filter Accountings to count.
   * @example
   * // Count the number of Accountings
   * const count = await prisma.accounting.count({
   *   where: {
   *     // ... the filter for the Accountings we want to count
   *   }
   * })
  **/
  count<T extends AccountingCountArgs>(
    args?: Prisma.Subset<T, AccountingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Accounting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountingAggregateArgs>(args: Prisma.Subset<T, AccountingAggregateArgs>): Prisma.PrismaPromise<GetAccountingAggregateType<T>>

  /**
   * Group by Accounting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountingGroupByArgs['orderBy'] }
      : { orderBy?: AccountingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Accounting model
 */
readonly fields: AccountingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Accounting.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  parent<T extends Prisma.Accounting$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Accounting$parentArgs<ExtArgs>>): Prisma.Prisma__AccountingClient<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.Accounting$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Accounting$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  lines<T extends Prisma.Accounting$linesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Accounting$linesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  invoiceLines<T extends Prisma.Accounting$invoiceLinesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Accounting$invoiceLinesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  billLines<T extends Prisma.Accounting$billLinesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Accounting$billLinesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BillLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Accounting model
 */
export interface AccountingFieldRefs {
  readonly id: Prisma.FieldRef<"Accounting", 'String'>
  readonly code: Prisma.FieldRef<"Accounting", 'String'>
  readonly name: Prisma.FieldRef<"Accounting", 'String'>
  readonly type: Prisma.FieldRef<"Accounting", 'AccountType'>
  readonly parentId: Prisma.FieldRef<"Accounting", 'String'>
  readonly isActive: Prisma.FieldRef<"Accounting", 'Boolean'>
  readonly balance: Prisma.FieldRef<"Accounting", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"Accounting", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Accounting", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Accounting findUnique
 */
export type AccountingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * Filter, which Accounting to fetch.
   */
  where: Prisma.AccountingWhereUniqueInput
}

/**
 * Accounting findUniqueOrThrow
 */
export type AccountingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * Filter, which Accounting to fetch.
   */
  where: Prisma.AccountingWhereUniqueInput
}

/**
 * Accounting findFirst
 */
export type AccountingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * Filter, which Accounting to fetch.
   */
  where?: Prisma.AccountingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accountings to fetch.
   */
  orderBy?: Prisma.AccountingOrderByWithRelationInput | Prisma.AccountingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Accountings.
   */
  cursor?: Prisma.AccountingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accountings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accountings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accountings.
   */
  distinct?: Prisma.AccountingScalarFieldEnum | Prisma.AccountingScalarFieldEnum[]
}

/**
 * Accounting findFirstOrThrow
 */
export type AccountingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * Filter, which Accounting to fetch.
   */
  where?: Prisma.AccountingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accountings to fetch.
   */
  orderBy?: Prisma.AccountingOrderByWithRelationInput | Prisma.AccountingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Accountings.
   */
  cursor?: Prisma.AccountingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accountings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accountings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accountings.
   */
  distinct?: Prisma.AccountingScalarFieldEnum | Prisma.AccountingScalarFieldEnum[]
}

/**
 * Accounting findMany
 */
export type AccountingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * Filter, which Accountings to fetch.
   */
  where?: Prisma.AccountingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accountings to fetch.
   */
  orderBy?: Prisma.AccountingOrderByWithRelationInput | Prisma.AccountingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Accountings.
   */
  cursor?: Prisma.AccountingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accountings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accountings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accountings.
   */
  distinct?: Prisma.AccountingScalarFieldEnum | Prisma.AccountingScalarFieldEnum[]
}

/**
 * Accounting create
 */
export type AccountingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * The data needed to create a Accounting.
   */
  data: Prisma.XOR<Prisma.AccountingCreateInput, Prisma.AccountingUncheckedCreateInput>
}

/**
 * Accounting createMany
 */
export type AccountingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Accountings.
   */
  data: Prisma.AccountingCreateManyInput | Prisma.AccountingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Accounting createManyAndReturn
 */
export type AccountingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * The data used to create many Accountings.
   */
  data: Prisma.AccountingCreateManyInput | Prisma.AccountingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Accounting update
 */
export type AccountingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * The data needed to update a Accounting.
   */
  data: Prisma.XOR<Prisma.AccountingUpdateInput, Prisma.AccountingUncheckedUpdateInput>
  /**
   * Choose, which Accounting to update.
   */
  where: Prisma.AccountingWhereUniqueInput
}

/**
 * Accounting updateMany
 */
export type AccountingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Accountings.
   */
  data: Prisma.XOR<Prisma.AccountingUpdateManyMutationInput, Prisma.AccountingUncheckedUpdateManyInput>
  /**
   * Filter which Accountings to update
   */
  where?: Prisma.AccountingWhereInput
  /**
   * Limit how many Accountings to update.
   */
  limit?: number
}

/**
 * Accounting updateManyAndReturn
 */
export type AccountingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * The data used to update Accountings.
   */
  data: Prisma.XOR<Prisma.AccountingUpdateManyMutationInput, Prisma.AccountingUncheckedUpdateManyInput>
  /**
   * Filter which Accountings to update
   */
  where?: Prisma.AccountingWhereInput
  /**
   * Limit how many Accountings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Accounting upsert
 */
export type AccountingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * The filter to search for the Accounting to update in case it exists.
   */
  where: Prisma.AccountingWhereUniqueInput
  /**
   * In case the Accounting found by the `where` argument doesn't exist, create a new Accounting with this data.
   */
  create: Prisma.XOR<Prisma.AccountingCreateInput, Prisma.AccountingUncheckedCreateInput>
  /**
   * In case the Accounting was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountingUpdateInput, Prisma.AccountingUncheckedUpdateInput>
}

/**
 * Accounting delete
 */
export type AccountingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  /**
   * Filter which Accounting to delete.
   */
  where: Prisma.AccountingWhereUniqueInput
}

/**
 * Accounting deleteMany
 */
export type AccountingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Accountings to delete
   */
  where?: Prisma.AccountingWhereInput
  /**
   * Limit how many Accountings to delete.
   */
  limit?: number
}

/**
 * Accounting.parent
 */
export type Accounting$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  where?: Prisma.AccountingWhereInput
}

/**
 * Accounting.children
 */
export type Accounting$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
  where?: Prisma.AccountingWhereInput
  orderBy?: Prisma.AccountingOrderByWithRelationInput | Prisma.AccountingOrderByWithRelationInput[]
  cursor?: Prisma.AccountingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccountingScalarFieldEnum | Prisma.AccountingScalarFieldEnum[]
}

/**
 * Accounting.lines
 */
export type Accounting$linesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalLine
   */
  select?: Prisma.JournalLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalLine
   */
  omit?: Prisma.JournalLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalLineInclude<ExtArgs> | null
  where?: Prisma.JournalLineWhereInput
  orderBy?: Prisma.JournalLineOrderByWithRelationInput | Prisma.JournalLineOrderByWithRelationInput[]
  cursor?: Prisma.JournalLineWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JournalLineScalarFieldEnum | Prisma.JournalLineScalarFieldEnum[]
}

/**
 * Accounting.invoiceLines
 */
export type Accounting$invoiceLinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceLine
   */
  select?: Prisma.InvoiceLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceLine
   */
  omit?: Prisma.InvoiceLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceLineInclude<ExtArgs> | null
  where?: Prisma.InvoiceLineWhereInput
  orderBy?: Prisma.InvoiceLineOrderByWithRelationInput | Prisma.InvoiceLineOrderByWithRelationInput[]
  cursor?: Prisma.InvoiceLineWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvoiceLineScalarFieldEnum | Prisma.InvoiceLineScalarFieldEnum[]
}

/**
 * Accounting.billLines
 */
export type Accounting$billLinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BillLine
   */
  select?: Prisma.BillLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BillLine
   */
  omit?: Prisma.BillLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillLineInclude<ExtArgs> | null
  where?: Prisma.BillLineWhereInput
  orderBy?: Prisma.BillLineOrderByWithRelationInput | Prisma.BillLineOrderByWithRelationInput[]
  cursor?: Prisma.BillLineWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BillLineScalarFieldEnum | Prisma.BillLineScalarFieldEnum[]
}

/**
 * Accounting without action
 */
export type AccountingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accounting
   */
  select?: Prisma.AccountingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accounting
   */
  omit?: Prisma.AccountingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountingInclude<ExtArgs> | null
}
