
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RoutingStep` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RoutingStep
 * 
 */
export type RoutingStepModel = runtime.Types.Result.DefaultSelection<Prisma.$RoutingStepPayload>

export type AggregateRoutingStep = {
  _count: RoutingStepCountAggregateOutputType | null
  _avg: RoutingStepAvgAggregateOutputType | null
  _sum: RoutingStepSumAggregateOutputType | null
  _min: RoutingStepMinAggregateOutputType | null
  _max: RoutingStepMaxAggregateOutputType | null
}

export type RoutingStepAvgAggregateOutputType = {
  stepOrder: number | null
  estimatedMinutes: number | null
}

export type RoutingStepSumAggregateOutputType = {
  stepOrder: number | null
  estimatedMinutes: number | null
}

export type RoutingStepMinAggregateOutputType = {
  id: string | null
  routingTemplateId: string | null
  stepOrder: number | null
  operationName: string | null
  defaultMachineType: string | null
  defaultMachineId: string | null
  estimatedMinutes: number | null
}

export type RoutingStepMaxAggregateOutputType = {
  id: string | null
  routingTemplateId: string | null
  stepOrder: number | null
  operationName: string | null
  defaultMachineType: string | null
  defaultMachineId: string | null
  estimatedMinutes: number | null
}

export type RoutingStepCountAggregateOutputType = {
  id: number
  routingTemplateId: number
  stepOrder: number
  operationName: number
  defaultMachineType: number
  defaultMachineId: number
  estimatedMinutes: number
  _all: number
}


export type RoutingStepAvgAggregateInputType = {
  stepOrder?: true
  estimatedMinutes?: true
}

export type RoutingStepSumAggregateInputType = {
  stepOrder?: true
  estimatedMinutes?: true
}

export type RoutingStepMinAggregateInputType = {
  id?: true
  routingTemplateId?: true
  stepOrder?: true
  operationName?: true
  defaultMachineType?: true
  defaultMachineId?: true
  estimatedMinutes?: true
}

export type RoutingStepMaxAggregateInputType = {
  id?: true
  routingTemplateId?: true
  stepOrder?: true
  operationName?: true
  defaultMachineType?: true
  defaultMachineId?: true
  estimatedMinutes?: true
}

export type RoutingStepCountAggregateInputType = {
  id?: true
  routingTemplateId?: true
  stepOrder?: true
  operationName?: true
  defaultMachineType?: true
  defaultMachineId?: true
  estimatedMinutes?: true
  _all?: true
}

export type RoutingStepAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoutingStep to aggregate.
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoutingSteps to fetch.
   */
  orderBy?: Prisma.RoutingStepOrderByWithRelationInput | Prisma.RoutingStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RoutingStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoutingSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoutingSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RoutingSteps
  **/
  _count?: true | RoutingStepCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RoutingStepAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RoutingStepSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RoutingStepMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RoutingStepMaxAggregateInputType
}

export type GetRoutingStepAggregateType<T extends RoutingStepAggregateArgs> = {
      [P in keyof T & keyof AggregateRoutingStep]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRoutingStep[P]>
    : Prisma.GetScalarType<T[P], AggregateRoutingStep[P]>
}




export type RoutingStepGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoutingStepWhereInput
  orderBy?: Prisma.RoutingStepOrderByWithAggregationInput | Prisma.RoutingStepOrderByWithAggregationInput[]
  by: Prisma.RoutingStepScalarFieldEnum[] | Prisma.RoutingStepScalarFieldEnum
  having?: Prisma.RoutingStepScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RoutingStepCountAggregateInputType | true
  _avg?: RoutingStepAvgAggregateInputType
  _sum?: RoutingStepSumAggregateInputType
  _min?: RoutingStepMinAggregateInputType
  _max?: RoutingStepMaxAggregateInputType
}

export type RoutingStepGroupByOutputType = {
  id: string
  routingTemplateId: string
  stepOrder: number
  operationName: string
  defaultMachineType: string | null
  defaultMachineId: string | null
  estimatedMinutes: number | null
  _count: RoutingStepCountAggregateOutputType | null
  _avg: RoutingStepAvgAggregateOutputType | null
  _sum: RoutingStepSumAggregateOutputType | null
  _min: RoutingStepMinAggregateOutputType | null
  _max: RoutingStepMaxAggregateOutputType | null
}

export type GetRoutingStepGroupByPayload<T extends RoutingStepGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RoutingStepGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RoutingStepGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RoutingStepGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RoutingStepGroupByOutputType[P]>
      }
    >
  >



export type RoutingStepWhereInput = {
  AND?: Prisma.RoutingStepWhereInput | Prisma.RoutingStepWhereInput[]
  OR?: Prisma.RoutingStepWhereInput[]
  NOT?: Prisma.RoutingStepWhereInput | Prisma.RoutingStepWhereInput[]
  id?: Prisma.StringFilter<"RoutingStep"> | string
  routingTemplateId?: Prisma.StringFilter<"RoutingStep"> | string
  stepOrder?: Prisma.IntFilter<"RoutingStep"> | number
  operationName?: Prisma.StringFilter<"RoutingStep"> | string
  defaultMachineType?: Prisma.StringNullableFilter<"RoutingStep"> | string | null
  defaultMachineId?: Prisma.StringNullableFilter<"RoutingStep"> | string | null
  estimatedMinutes?: Prisma.IntNullableFilter<"RoutingStep"> | number | null
  operations?: Prisma.OperationListRelationFilter
  routing?: Prisma.XOR<Prisma.RoutingTemplateScalarRelationFilter, Prisma.RoutingTemplateWhereInput>
  defaultMachine?: Prisma.XOR<Prisma.MachineNullableScalarRelationFilter, Prisma.MachineWhereInput> | null
}

export type RoutingStepOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  routingTemplateId?: Prisma.SortOrder
  stepOrder?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  defaultMachineType?: Prisma.SortOrderInput | Prisma.SortOrder
  defaultMachineId?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  operations?: Prisma.OperationOrderByRelationAggregateInput
  routing?: Prisma.RoutingTemplateOrderByWithRelationInput
  defaultMachine?: Prisma.MachineOrderByWithRelationInput
}

export type RoutingStepWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  routingTemplateId_stepOrder?: Prisma.RoutingStepRoutingTemplateIdStepOrderCompoundUniqueInput
  AND?: Prisma.RoutingStepWhereInput | Prisma.RoutingStepWhereInput[]
  OR?: Prisma.RoutingStepWhereInput[]
  NOT?: Prisma.RoutingStepWhereInput | Prisma.RoutingStepWhereInput[]
  routingTemplateId?: Prisma.StringFilter<"RoutingStep"> | string
  stepOrder?: Prisma.IntFilter<"RoutingStep"> | number
  operationName?: Prisma.StringFilter<"RoutingStep"> | string
  defaultMachineType?: Prisma.StringNullableFilter<"RoutingStep"> | string | null
  defaultMachineId?: Prisma.StringNullableFilter<"RoutingStep"> | string | null
  estimatedMinutes?: Prisma.IntNullableFilter<"RoutingStep"> | number | null
  operations?: Prisma.OperationListRelationFilter
  routing?: Prisma.XOR<Prisma.RoutingTemplateScalarRelationFilter, Prisma.RoutingTemplateWhereInput>
  defaultMachine?: Prisma.XOR<Prisma.MachineNullableScalarRelationFilter, Prisma.MachineWhereInput> | null
}, "id" | "routingTemplateId_stepOrder">

export type RoutingStepOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  routingTemplateId?: Prisma.SortOrder
  stepOrder?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  defaultMachineType?: Prisma.SortOrderInput | Prisma.SortOrder
  defaultMachineId?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RoutingStepCountOrderByAggregateInput
  _avg?: Prisma.RoutingStepAvgOrderByAggregateInput
  _max?: Prisma.RoutingStepMaxOrderByAggregateInput
  _min?: Prisma.RoutingStepMinOrderByAggregateInput
  _sum?: Prisma.RoutingStepSumOrderByAggregateInput
}

export type RoutingStepScalarWhereWithAggregatesInput = {
  AND?: Prisma.RoutingStepScalarWhereWithAggregatesInput | Prisma.RoutingStepScalarWhereWithAggregatesInput[]
  OR?: Prisma.RoutingStepScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RoutingStepScalarWhereWithAggregatesInput | Prisma.RoutingStepScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RoutingStep"> | string
  routingTemplateId?: Prisma.StringWithAggregatesFilter<"RoutingStep"> | string
  stepOrder?: Prisma.IntWithAggregatesFilter<"RoutingStep"> | number
  operationName?: Prisma.StringWithAggregatesFilter<"RoutingStep"> | string
  defaultMachineType?: Prisma.StringNullableWithAggregatesFilter<"RoutingStep"> | string | null
  defaultMachineId?: Prisma.StringNullableWithAggregatesFilter<"RoutingStep"> | string | null
  estimatedMinutes?: Prisma.IntNullableWithAggregatesFilter<"RoutingStep"> | number | null
}

export type RoutingStepCreateInput = {
  id?: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  estimatedMinutes?: number | null
  operations?: Prisma.OperationCreateNestedManyWithoutRoutingStepInput
  routing: Prisma.RoutingTemplateCreateNestedOneWithoutStepsInput
  defaultMachine?: Prisma.MachineCreateNestedOneWithoutDefaultStepsInput
}

export type RoutingStepUncheckedCreateInput = {
  id?: string
  routingTemplateId: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  defaultMachineId?: string | null
  estimatedMinutes?: number | null
  operations?: Prisma.OperationUncheckedCreateNestedManyWithoutRoutingStepInput
}

export type RoutingStepUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  operations?: Prisma.OperationUpdateManyWithoutRoutingStepNestedInput
  routing?: Prisma.RoutingTemplateUpdateOneRequiredWithoutStepsNestedInput
  defaultMachine?: Prisma.MachineUpdateOneWithoutDefaultStepsNestedInput
}

export type RoutingStepUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  routingTemplateId?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultMachineId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  operations?: Prisma.OperationUncheckedUpdateManyWithoutRoutingStepNestedInput
}

export type RoutingStepCreateManyInput = {
  id?: string
  routingTemplateId: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  defaultMachineId?: string | null
  estimatedMinutes?: number | null
}

export type RoutingStepUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RoutingStepUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  routingTemplateId?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultMachineId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RoutingStepListRelationFilter = {
  every?: Prisma.RoutingStepWhereInput
  some?: Prisma.RoutingStepWhereInput
  none?: Prisma.RoutingStepWhereInput
}

export type RoutingStepOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RoutingStepRoutingTemplateIdStepOrderCompoundUniqueInput = {
  routingTemplateId: string
  stepOrder: number
}

export type RoutingStepCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  routingTemplateId?: Prisma.SortOrder
  stepOrder?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  defaultMachineType?: Prisma.SortOrder
  defaultMachineId?: Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrder
}

export type RoutingStepAvgOrderByAggregateInput = {
  stepOrder?: Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrder
}

export type RoutingStepMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  routingTemplateId?: Prisma.SortOrder
  stepOrder?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  defaultMachineType?: Prisma.SortOrder
  defaultMachineId?: Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrder
}

export type RoutingStepMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  routingTemplateId?: Prisma.SortOrder
  stepOrder?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  defaultMachineType?: Prisma.SortOrder
  defaultMachineId?: Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrder
}

export type RoutingStepSumOrderByAggregateInput = {
  stepOrder?: Prisma.SortOrder
  estimatedMinutes?: Prisma.SortOrder
}

export type RoutingStepScalarRelationFilter = {
  is?: Prisma.RoutingStepWhereInput
  isNot?: Prisma.RoutingStepWhereInput
}

export type RoutingStepCreateNestedManyWithoutRoutingInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutRoutingInput, Prisma.RoutingStepUncheckedCreateWithoutRoutingInput> | Prisma.RoutingStepCreateWithoutRoutingInput[] | Prisma.RoutingStepUncheckedCreateWithoutRoutingInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutRoutingInput | Prisma.RoutingStepCreateOrConnectWithoutRoutingInput[]
  createMany?: Prisma.RoutingStepCreateManyRoutingInputEnvelope
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
}

export type RoutingStepUncheckedCreateNestedManyWithoutRoutingInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutRoutingInput, Prisma.RoutingStepUncheckedCreateWithoutRoutingInput> | Prisma.RoutingStepCreateWithoutRoutingInput[] | Prisma.RoutingStepUncheckedCreateWithoutRoutingInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutRoutingInput | Prisma.RoutingStepCreateOrConnectWithoutRoutingInput[]
  createMany?: Prisma.RoutingStepCreateManyRoutingInputEnvelope
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
}

export type RoutingStepUpdateManyWithoutRoutingNestedInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutRoutingInput, Prisma.RoutingStepUncheckedCreateWithoutRoutingInput> | Prisma.RoutingStepCreateWithoutRoutingInput[] | Prisma.RoutingStepUncheckedCreateWithoutRoutingInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutRoutingInput | Prisma.RoutingStepCreateOrConnectWithoutRoutingInput[]
  upsert?: Prisma.RoutingStepUpsertWithWhereUniqueWithoutRoutingInput | Prisma.RoutingStepUpsertWithWhereUniqueWithoutRoutingInput[]
  createMany?: Prisma.RoutingStepCreateManyRoutingInputEnvelope
  set?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  disconnect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  delete?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  update?: Prisma.RoutingStepUpdateWithWhereUniqueWithoutRoutingInput | Prisma.RoutingStepUpdateWithWhereUniqueWithoutRoutingInput[]
  updateMany?: Prisma.RoutingStepUpdateManyWithWhereWithoutRoutingInput | Prisma.RoutingStepUpdateManyWithWhereWithoutRoutingInput[]
  deleteMany?: Prisma.RoutingStepScalarWhereInput | Prisma.RoutingStepScalarWhereInput[]
}

export type RoutingStepUncheckedUpdateManyWithoutRoutingNestedInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutRoutingInput, Prisma.RoutingStepUncheckedCreateWithoutRoutingInput> | Prisma.RoutingStepCreateWithoutRoutingInput[] | Prisma.RoutingStepUncheckedCreateWithoutRoutingInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutRoutingInput | Prisma.RoutingStepCreateOrConnectWithoutRoutingInput[]
  upsert?: Prisma.RoutingStepUpsertWithWhereUniqueWithoutRoutingInput | Prisma.RoutingStepUpsertWithWhereUniqueWithoutRoutingInput[]
  createMany?: Prisma.RoutingStepCreateManyRoutingInputEnvelope
  set?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  disconnect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  delete?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  update?: Prisma.RoutingStepUpdateWithWhereUniqueWithoutRoutingInput | Prisma.RoutingStepUpdateWithWhereUniqueWithoutRoutingInput[]
  updateMany?: Prisma.RoutingStepUpdateManyWithWhereWithoutRoutingInput | Prisma.RoutingStepUpdateManyWithWhereWithoutRoutingInput[]
  deleteMany?: Prisma.RoutingStepScalarWhereInput | Prisma.RoutingStepScalarWhereInput[]
}

export type RoutingStepCreateNestedManyWithoutDefaultMachineInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput> | Prisma.RoutingStepCreateWithoutDefaultMachineInput[] | Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput | Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput[]
  createMany?: Prisma.RoutingStepCreateManyDefaultMachineInputEnvelope
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
}

export type RoutingStepUncheckedCreateNestedManyWithoutDefaultMachineInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput> | Prisma.RoutingStepCreateWithoutDefaultMachineInput[] | Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput | Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput[]
  createMany?: Prisma.RoutingStepCreateManyDefaultMachineInputEnvelope
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
}

export type RoutingStepUpdateManyWithoutDefaultMachineNestedInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput> | Prisma.RoutingStepCreateWithoutDefaultMachineInput[] | Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput | Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput[]
  upsert?: Prisma.RoutingStepUpsertWithWhereUniqueWithoutDefaultMachineInput | Prisma.RoutingStepUpsertWithWhereUniqueWithoutDefaultMachineInput[]
  createMany?: Prisma.RoutingStepCreateManyDefaultMachineInputEnvelope
  set?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  disconnect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  delete?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  update?: Prisma.RoutingStepUpdateWithWhereUniqueWithoutDefaultMachineInput | Prisma.RoutingStepUpdateWithWhereUniqueWithoutDefaultMachineInput[]
  updateMany?: Prisma.RoutingStepUpdateManyWithWhereWithoutDefaultMachineInput | Prisma.RoutingStepUpdateManyWithWhereWithoutDefaultMachineInput[]
  deleteMany?: Prisma.RoutingStepScalarWhereInput | Prisma.RoutingStepScalarWhereInput[]
}

export type RoutingStepUncheckedUpdateManyWithoutDefaultMachineNestedInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput> | Prisma.RoutingStepCreateWithoutDefaultMachineInput[] | Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput[]
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput | Prisma.RoutingStepCreateOrConnectWithoutDefaultMachineInput[]
  upsert?: Prisma.RoutingStepUpsertWithWhereUniqueWithoutDefaultMachineInput | Prisma.RoutingStepUpsertWithWhereUniqueWithoutDefaultMachineInput[]
  createMany?: Prisma.RoutingStepCreateManyDefaultMachineInputEnvelope
  set?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  disconnect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  delete?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  connect?: Prisma.RoutingStepWhereUniqueInput | Prisma.RoutingStepWhereUniqueInput[]
  update?: Prisma.RoutingStepUpdateWithWhereUniqueWithoutDefaultMachineInput | Prisma.RoutingStepUpdateWithWhereUniqueWithoutDefaultMachineInput[]
  updateMany?: Prisma.RoutingStepUpdateManyWithWhereWithoutDefaultMachineInput | Prisma.RoutingStepUpdateManyWithWhereWithoutDefaultMachineInput[]
  deleteMany?: Prisma.RoutingStepScalarWhereInput | Prisma.RoutingStepScalarWhereInput[]
}

export type RoutingStepCreateNestedOneWithoutOperationsInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutOperationsInput, Prisma.RoutingStepUncheckedCreateWithoutOperationsInput>
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutOperationsInput
  connect?: Prisma.RoutingStepWhereUniqueInput
}

export type RoutingStepUpdateOneRequiredWithoutOperationsNestedInput = {
  create?: Prisma.XOR<Prisma.RoutingStepCreateWithoutOperationsInput, Prisma.RoutingStepUncheckedCreateWithoutOperationsInput>
  connectOrCreate?: Prisma.RoutingStepCreateOrConnectWithoutOperationsInput
  upsert?: Prisma.RoutingStepUpsertWithoutOperationsInput
  connect?: Prisma.RoutingStepWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RoutingStepUpdateToOneWithWhereWithoutOperationsInput, Prisma.RoutingStepUpdateWithoutOperationsInput>, Prisma.RoutingStepUncheckedUpdateWithoutOperationsInput>
}

export type RoutingStepCreateWithoutRoutingInput = {
  id?: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  estimatedMinutes?: number | null
  operations?: Prisma.OperationCreateNestedManyWithoutRoutingStepInput
  defaultMachine?: Prisma.MachineCreateNestedOneWithoutDefaultStepsInput
}

export type RoutingStepUncheckedCreateWithoutRoutingInput = {
  id?: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  defaultMachineId?: string | null
  estimatedMinutes?: number | null
  operations?: Prisma.OperationUncheckedCreateNestedManyWithoutRoutingStepInput
}

export type RoutingStepCreateOrConnectWithoutRoutingInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  create: Prisma.XOR<Prisma.RoutingStepCreateWithoutRoutingInput, Prisma.RoutingStepUncheckedCreateWithoutRoutingInput>
}

export type RoutingStepCreateManyRoutingInputEnvelope = {
  data: Prisma.RoutingStepCreateManyRoutingInput | Prisma.RoutingStepCreateManyRoutingInput[]
  skipDuplicates?: boolean
}

export type RoutingStepUpsertWithWhereUniqueWithoutRoutingInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  update: Prisma.XOR<Prisma.RoutingStepUpdateWithoutRoutingInput, Prisma.RoutingStepUncheckedUpdateWithoutRoutingInput>
  create: Prisma.XOR<Prisma.RoutingStepCreateWithoutRoutingInput, Prisma.RoutingStepUncheckedCreateWithoutRoutingInput>
}

export type RoutingStepUpdateWithWhereUniqueWithoutRoutingInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  data: Prisma.XOR<Prisma.RoutingStepUpdateWithoutRoutingInput, Prisma.RoutingStepUncheckedUpdateWithoutRoutingInput>
}

export type RoutingStepUpdateManyWithWhereWithoutRoutingInput = {
  where: Prisma.RoutingStepScalarWhereInput
  data: Prisma.XOR<Prisma.RoutingStepUpdateManyMutationInput, Prisma.RoutingStepUncheckedUpdateManyWithoutRoutingInput>
}

export type RoutingStepScalarWhereInput = {
  AND?: Prisma.RoutingStepScalarWhereInput | Prisma.RoutingStepScalarWhereInput[]
  OR?: Prisma.RoutingStepScalarWhereInput[]
  NOT?: Prisma.RoutingStepScalarWhereInput | Prisma.RoutingStepScalarWhereInput[]
  id?: Prisma.StringFilter<"RoutingStep"> | string
  routingTemplateId?: Prisma.StringFilter<"RoutingStep"> | string
  stepOrder?: Prisma.IntFilter<"RoutingStep"> | number
  operationName?: Prisma.StringFilter<"RoutingStep"> | string
  defaultMachineType?: Prisma.StringNullableFilter<"RoutingStep"> | string | null
  defaultMachineId?: Prisma.StringNullableFilter<"RoutingStep"> | string | null
  estimatedMinutes?: Prisma.IntNullableFilter<"RoutingStep"> | number | null
}

export type RoutingStepCreateWithoutDefaultMachineInput = {
  id?: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  estimatedMinutes?: number | null
  operations?: Prisma.OperationCreateNestedManyWithoutRoutingStepInput
  routing: Prisma.RoutingTemplateCreateNestedOneWithoutStepsInput
}

export type RoutingStepUncheckedCreateWithoutDefaultMachineInput = {
  id?: string
  routingTemplateId: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  estimatedMinutes?: number | null
  operations?: Prisma.OperationUncheckedCreateNestedManyWithoutRoutingStepInput
}

export type RoutingStepCreateOrConnectWithoutDefaultMachineInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  create: Prisma.XOR<Prisma.RoutingStepCreateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput>
}

export type RoutingStepCreateManyDefaultMachineInputEnvelope = {
  data: Prisma.RoutingStepCreateManyDefaultMachineInput | Prisma.RoutingStepCreateManyDefaultMachineInput[]
  skipDuplicates?: boolean
}

export type RoutingStepUpsertWithWhereUniqueWithoutDefaultMachineInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  update: Prisma.XOR<Prisma.RoutingStepUpdateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedUpdateWithoutDefaultMachineInput>
  create: Prisma.XOR<Prisma.RoutingStepCreateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedCreateWithoutDefaultMachineInput>
}

export type RoutingStepUpdateWithWhereUniqueWithoutDefaultMachineInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  data: Prisma.XOR<Prisma.RoutingStepUpdateWithoutDefaultMachineInput, Prisma.RoutingStepUncheckedUpdateWithoutDefaultMachineInput>
}

export type RoutingStepUpdateManyWithWhereWithoutDefaultMachineInput = {
  where: Prisma.RoutingStepScalarWhereInput
  data: Prisma.XOR<Prisma.RoutingStepUpdateManyMutationInput, Prisma.RoutingStepUncheckedUpdateManyWithoutDefaultMachineInput>
}

export type RoutingStepCreateWithoutOperationsInput = {
  id?: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  estimatedMinutes?: number | null
  routing: Prisma.RoutingTemplateCreateNestedOneWithoutStepsInput
  defaultMachine?: Prisma.MachineCreateNestedOneWithoutDefaultStepsInput
}

export type RoutingStepUncheckedCreateWithoutOperationsInput = {
  id?: string
  routingTemplateId: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  defaultMachineId?: string | null
  estimatedMinutes?: number | null
}

export type RoutingStepCreateOrConnectWithoutOperationsInput = {
  where: Prisma.RoutingStepWhereUniqueInput
  create: Prisma.XOR<Prisma.RoutingStepCreateWithoutOperationsInput, Prisma.RoutingStepUncheckedCreateWithoutOperationsInput>
}

export type RoutingStepUpsertWithoutOperationsInput = {
  update: Prisma.XOR<Prisma.RoutingStepUpdateWithoutOperationsInput, Prisma.RoutingStepUncheckedUpdateWithoutOperationsInput>
  create: Prisma.XOR<Prisma.RoutingStepCreateWithoutOperationsInput, Prisma.RoutingStepUncheckedCreateWithoutOperationsInput>
  where?: Prisma.RoutingStepWhereInput
}

export type RoutingStepUpdateToOneWithWhereWithoutOperationsInput = {
  where?: Prisma.RoutingStepWhereInput
  data: Prisma.XOR<Prisma.RoutingStepUpdateWithoutOperationsInput, Prisma.RoutingStepUncheckedUpdateWithoutOperationsInput>
}

export type RoutingStepUpdateWithoutOperationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  routing?: Prisma.RoutingTemplateUpdateOneRequiredWithoutStepsNestedInput
  defaultMachine?: Prisma.MachineUpdateOneWithoutDefaultStepsNestedInput
}

export type RoutingStepUncheckedUpdateWithoutOperationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  routingTemplateId?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultMachineId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RoutingStepCreateManyRoutingInput = {
  id?: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  defaultMachineId?: string | null
  estimatedMinutes?: number | null
}

export type RoutingStepUpdateWithoutRoutingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  operations?: Prisma.OperationUpdateManyWithoutRoutingStepNestedInput
  defaultMachine?: Prisma.MachineUpdateOneWithoutDefaultStepsNestedInput
}

export type RoutingStepUncheckedUpdateWithoutRoutingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultMachineId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  operations?: Prisma.OperationUncheckedUpdateManyWithoutRoutingStepNestedInput
}

export type RoutingStepUncheckedUpdateManyWithoutRoutingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  defaultMachineId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RoutingStepCreateManyDefaultMachineInput = {
  id?: string
  routingTemplateId: string
  stepOrder: number
  operationName: string
  defaultMachineType?: string | null
  estimatedMinutes?: number | null
}

export type RoutingStepUpdateWithoutDefaultMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  operations?: Prisma.OperationUpdateManyWithoutRoutingStepNestedInput
  routing?: Prisma.RoutingTemplateUpdateOneRequiredWithoutStepsNestedInput
}

export type RoutingStepUncheckedUpdateWithoutDefaultMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  routingTemplateId?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  operations?: Prisma.OperationUncheckedUpdateManyWithoutRoutingStepNestedInput
}

export type RoutingStepUncheckedUpdateManyWithoutDefaultMachineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  routingTemplateId?: Prisma.StringFieldUpdateOperationsInput | string
  stepOrder?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  defaultMachineType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type RoutingStepCountOutputType
 */

export type RoutingStepCountOutputType = {
  operations: number
}

export type RoutingStepCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operations?: boolean | RoutingStepCountOutputTypeCountOperationsArgs
}

/**
 * RoutingStepCountOutputType without action
 */
export type RoutingStepCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStepCountOutputType
   */
  select?: Prisma.RoutingStepCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RoutingStepCountOutputType without action
 */
export type RoutingStepCountOutputTypeCountOperationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OperationWhereInput
}


export type RoutingStepSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  routingTemplateId?: boolean
  stepOrder?: boolean
  operationName?: boolean
  defaultMachineType?: boolean
  defaultMachineId?: boolean
  estimatedMinutes?: boolean
  operations?: boolean | Prisma.RoutingStep$operationsArgs<ExtArgs>
  routing?: boolean | Prisma.RoutingTemplateDefaultArgs<ExtArgs>
  defaultMachine?: boolean | Prisma.RoutingStep$defaultMachineArgs<ExtArgs>
  _count?: boolean | Prisma.RoutingStepCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["routingStep"]>

export type RoutingStepSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  routingTemplateId?: boolean
  stepOrder?: boolean
  operationName?: boolean
  defaultMachineType?: boolean
  defaultMachineId?: boolean
  estimatedMinutes?: boolean
  routing?: boolean | Prisma.RoutingTemplateDefaultArgs<ExtArgs>
  defaultMachine?: boolean | Prisma.RoutingStep$defaultMachineArgs<ExtArgs>
}, ExtArgs["result"]["routingStep"]>

export type RoutingStepSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  routingTemplateId?: boolean
  stepOrder?: boolean
  operationName?: boolean
  defaultMachineType?: boolean
  defaultMachineId?: boolean
  estimatedMinutes?: boolean
  routing?: boolean | Prisma.RoutingTemplateDefaultArgs<ExtArgs>
  defaultMachine?: boolean | Prisma.RoutingStep$defaultMachineArgs<ExtArgs>
}, ExtArgs["result"]["routingStep"]>

export type RoutingStepSelectScalar = {
  id?: boolean
  routingTemplateId?: boolean
  stepOrder?: boolean
  operationName?: boolean
  defaultMachineType?: boolean
  defaultMachineId?: boolean
  estimatedMinutes?: boolean
}

export type RoutingStepOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "routingTemplateId" | "stepOrder" | "operationName" | "defaultMachineType" | "defaultMachineId" | "estimatedMinutes", ExtArgs["result"]["routingStep"]>
export type RoutingStepInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operations?: boolean | Prisma.RoutingStep$operationsArgs<ExtArgs>
  routing?: boolean | Prisma.RoutingTemplateDefaultArgs<ExtArgs>
  defaultMachine?: boolean | Prisma.RoutingStep$defaultMachineArgs<ExtArgs>
  _count?: boolean | Prisma.RoutingStepCountOutputTypeDefaultArgs<ExtArgs>
}
export type RoutingStepIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  routing?: boolean | Prisma.RoutingTemplateDefaultArgs<ExtArgs>
  defaultMachine?: boolean | Prisma.RoutingStep$defaultMachineArgs<ExtArgs>
}
export type RoutingStepIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  routing?: boolean | Prisma.RoutingTemplateDefaultArgs<ExtArgs>
  defaultMachine?: boolean | Prisma.RoutingStep$defaultMachineArgs<ExtArgs>
}

export type $RoutingStepPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RoutingStep"
  objects: {
    operations: Prisma.$OperationPayload<ExtArgs>[]
    routing: Prisma.$RoutingTemplatePayload<ExtArgs>
    defaultMachine: Prisma.$MachinePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    routingTemplateId: string
    stepOrder: number
    operationName: string
    defaultMachineType: string | null
    defaultMachineId: string | null
    estimatedMinutes: number | null
  }, ExtArgs["result"]["routingStep"]>
  composites: {}
}

export type RoutingStepGetPayload<S extends boolean | null | undefined | RoutingStepDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload, S>

export type RoutingStepCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RoutingStepFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RoutingStepCountAggregateInputType | true
  }

export interface RoutingStepDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RoutingStep'], meta: { name: 'RoutingStep' } }
  /**
   * Find zero or one RoutingStep that matches the filter.
   * @param {RoutingStepFindUniqueArgs} args - Arguments to find a RoutingStep
   * @example
   * // Get one RoutingStep
   * const routingStep = await prisma.routingStep.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RoutingStepFindUniqueArgs>(args: Prisma.SelectSubset<T, RoutingStepFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RoutingStep that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RoutingStepFindUniqueOrThrowArgs} args - Arguments to find a RoutingStep
   * @example
   * // Get one RoutingStep
   * const routingStep = await prisma.routingStep.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RoutingStepFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RoutingStepFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoutingStep that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepFindFirstArgs} args - Arguments to find a RoutingStep
   * @example
   * // Get one RoutingStep
   * const routingStep = await prisma.routingStep.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RoutingStepFindFirstArgs>(args?: Prisma.SelectSubset<T, RoutingStepFindFirstArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoutingStep that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepFindFirstOrThrowArgs} args - Arguments to find a RoutingStep
   * @example
   * // Get one RoutingStep
   * const routingStep = await prisma.routingStep.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RoutingStepFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RoutingStepFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RoutingSteps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RoutingSteps
   * const routingSteps = await prisma.routingStep.findMany()
   * 
   * // Get first 10 RoutingSteps
   * const routingSteps = await prisma.routingStep.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const routingStepWithIdOnly = await prisma.routingStep.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RoutingStepFindManyArgs>(args?: Prisma.SelectSubset<T, RoutingStepFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RoutingStep.
   * @param {RoutingStepCreateArgs} args - Arguments to create a RoutingStep.
   * @example
   * // Create one RoutingStep
   * const RoutingStep = await prisma.routingStep.create({
   *   data: {
   *     // ... data to create a RoutingStep
   *   }
   * })
   * 
   */
  create<T extends RoutingStepCreateArgs>(args: Prisma.SelectSubset<T, RoutingStepCreateArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RoutingSteps.
   * @param {RoutingStepCreateManyArgs} args - Arguments to create many RoutingSteps.
   * @example
   * // Create many RoutingSteps
   * const routingStep = await prisma.routingStep.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RoutingStepCreateManyArgs>(args?: Prisma.SelectSubset<T, RoutingStepCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RoutingSteps and returns the data saved in the database.
   * @param {RoutingStepCreateManyAndReturnArgs} args - Arguments to create many RoutingSteps.
   * @example
   * // Create many RoutingSteps
   * const routingStep = await prisma.routingStep.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RoutingSteps and only return the `id`
   * const routingStepWithIdOnly = await prisma.routingStep.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RoutingStepCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RoutingStepCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RoutingStep.
   * @param {RoutingStepDeleteArgs} args - Arguments to delete one RoutingStep.
   * @example
   * // Delete one RoutingStep
   * const RoutingStep = await prisma.routingStep.delete({
   *   where: {
   *     // ... filter to delete one RoutingStep
   *   }
   * })
   * 
   */
  delete<T extends RoutingStepDeleteArgs>(args: Prisma.SelectSubset<T, RoutingStepDeleteArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RoutingStep.
   * @param {RoutingStepUpdateArgs} args - Arguments to update one RoutingStep.
   * @example
   * // Update one RoutingStep
   * const routingStep = await prisma.routingStep.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RoutingStepUpdateArgs>(args: Prisma.SelectSubset<T, RoutingStepUpdateArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RoutingSteps.
   * @param {RoutingStepDeleteManyArgs} args - Arguments to filter RoutingSteps to delete.
   * @example
   * // Delete a few RoutingSteps
   * const { count } = await prisma.routingStep.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RoutingStepDeleteManyArgs>(args?: Prisma.SelectSubset<T, RoutingStepDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoutingSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RoutingSteps
   * const routingStep = await prisma.routingStep.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RoutingStepUpdateManyArgs>(args: Prisma.SelectSubset<T, RoutingStepUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoutingSteps and returns the data updated in the database.
   * @param {RoutingStepUpdateManyAndReturnArgs} args - Arguments to update many RoutingSteps.
   * @example
   * // Update many RoutingSteps
   * const routingStep = await prisma.routingStep.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RoutingSteps and only return the `id`
   * const routingStepWithIdOnly = await prisma.routingStep.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RoutingStepUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RoutingStepUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RoutingStep.
   * @param {RoutingStepUpsertArgs} args - Arguments to update or create a RoutingStep.
   * @example
   * // Update or create a RoutingStep
   * const routingStep = await prisma.routingStep.upsert({
   *   create: {
   *     // ... data to create a RoutingStep
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RoutingStep we want to update
   *   }
   * })
   */
  upsert<T extends RoutingStepUpsertArgs>(args: Prisma.SelectSubset<T, RoutingStepUpsertArgs<ExtArgs>>): Prisma.Prisma__RoutingStepClient<runtime.Types.Result.GetResult<Prisma.$RoutingStepPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RoutingSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepCountArgs} args - Arguments to filter RoutingSteps to count.
   * @example
   * // Count the number of RoutingSteps
   * const count = await prisma.routingStep.count({
   *   where: {
   *     // ... the filter for the RoutingSteps we want to count
   *   }
   * })
  **/
  count<T extends RoutingStepCountArgs>(
    args?: Prisma.Subset<T, RoutingStepCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RoutingStepCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RoutingStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RoutingStepAggregateArgs>(args: Prisma.Subset<T, RoutingStepAggregateArgs>): Prisma.PrismaPromise<GetRoutingStepAggregateType<T>>

  /**
   * Group by RoutingStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoutingStepGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RoutingStepGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RoutingStepGroupByArgs['orderBy'] }
      : { orderBy?: RoutingStepGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RoutingStepGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRoutingStepGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RoutingStep model
 */
readonly fields: RoutingStepFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RoutingStep.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RoutingStepClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  operations<T extends Prisma.RoutingStep$operationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoutingStep$operationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OperationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  routing<T extends Prisma.RoutingTemplateDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoutingTemplateDefaultArgs<ExtArgs>>): Prisma.Prisma__RoutingTemplateClient<runtime.Types.Result.GetResult<Prisma.$RoutingTemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  defaultMachine<T extends Prisma.RoutingStep$defaultMachineArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoutingStep$defaultMachineArgs<ExtArgs>>): Prisma.Prisma__MachineClient<runtime.Types.Result.GetResult<Prisma.$MachinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RoutingStep model
 */
export interface RoutingStepFieldRefs {
  readonly id: Prisma.FieldRef<"RoutingStep", 'String'>
  readonly routingTemplateId: Prisma.FieldRef<"RoutingStep", 'String'>
  readonly stepOrder: Prisma.FieldRef<"RoutingStep", 'Int'>
  readonly operationName: Prisma.FieldRef<"RoutingStep", 'String'>
  readonly defaultMachineType: Prisma.FieldRef<"RoutingStep", 'String'>
  readonly defaultMachineId: Prisma.FieldRef<"RoutingStep", 'String'>
  readonly estimatedMinutes: Prisma.FieldRef<"RoutingStep", 'Int'>
}
    

// Custom InputTypes
/**
 * RoutingStep findUnique
 */
export type RoutingStepFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * Filter, which RoutingStep to fetch.
   */
  where: Prisma.RoutingStepWhereUniqueInput
}

/**
 * RoutingStep findUniqueOrThrow
 */
export type RoutingStepFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * Filter, which RoutingStep to fetch.
   */
  where: Prisma.RoutingStepWhereUniqueInput
}

/**
 * RoutingStep findFirst
 */
export type RoutingStepFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * Filter, which RoutingStep to fetch.
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoutingSteps to fetch.
   */
  orderBy?: Prisma.RoutingStepOrderByWithRelationInput | Prisma.RoutingStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoutingSteps.
   */
  cursor?: Prisma.RoutingStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoutingSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoutingSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoutingSteps.
   */
  distinct?: Prisma.RoutingStepScalarFieldEnum | Prisma.RoutingStepScalarFieldEnum[]
}

/**
 * RoutingStep findFirstOrThrow
 */
export type RoutingStepFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * Filter, which RoutingStep to fetch.
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoutingSteps to fetch.
   */
  orderBy?: Prisma.RoutingStepOrderByWithRelationInput | Prisma.RoutingStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoutingSteps.
   */
  cursor?: Prisma.RoutingStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoutingSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoutingSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoutingSteps.
   */
  distinct?: Prisma.RoutingStepScalarFieldEnum | Prisma.RoutingStepScalarFieldEnum[]
}

/**
 * RoutingStep findMany
 */
export type RoutingStepFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * Filter, which RoutingSteps to fetch.
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoutingSteps to fetch.
   */
  orderBy?: Prisma.RoutingStepOrderByWithRelationInput | Prisma.RoutingStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RoutingSteps.
   */
  cursor?: Prisma.RoutingStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoutingSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoutingSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoutingSteps.
   */
  distinct?: Prisma.RoutingStepScalarFieldEnum | Prisma.RoutingStepScalarFieldEnum[]
}

/**
 * RoutingStep create
 */
export type RoutingStepCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * The data needed to create a RoutingStep.
   */
  data: Prisma.XOR<Prisma.RoutingStepCreateInput, Prisma.RoutingStepUncheckedCreateInput>
}

/**
 * RoutingStep createMany
 */
export type RoutingStepCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RoutingSteps.
   */
  data: Prisma.RoutingStepCreateManyInput | Prisma.RoutingStepCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RoutingStep createManyAndReturn
 */
export type RoutingStepCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * The data used to create many RoutingSteps.
   */
  data: Prisma.RoutingStepCreateManyInput | Prisma.RoutingStepCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RoutingStep update
 */
export type RoutingStepUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * The data needed to update a RoutingStep.
   */
  data: Prisma.XOR<Prisma.RoutingStepUpdateInput, Prisma.RoutingStepUncheckedUpdateInput>
  /**
   * Choose, which RoutingStep to update.
   */
  where: Prisma.RoutingStepWhereUniqueInput
}

/**
 * RoutingStep updateMany
 */
export type RoutingStepUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RoutingSteps.
   */
  data: Prisma.XOR<Prisma.RoutingStepUpdateManyMutationInput, Prisma.RoutingStepUncheckedUpdateManyInput>
  /**
   * Filter which RoutingSteps to update
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * Limit how many RoutingSteps to update.
   */
  limit?: number
}

/**
 * RoutingStep updateManyAndReturn
 */
export type RoutingStepUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * The data used to update RoutingSteps.
   */
  data: Prisma.XOR<Prisma.RoutingStepUpdateManyMutationInput, Prisma.RoutingStepUncheckedUpdateManyInput>
  /**
   * Filter which RoutingSteps to update
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * Limit how many RoutingSteps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RoutingStep upsert
 */
export type RoutingStepUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * The filter to search for the RoutingStep to update in case it exists.
   */
  where: Prisma.RoutingStepWhereUniqueInput
  /**
   * In case the RoutingStep found by the `where` argument doesn't exist, create a new RoutingStep with this data.
   */
  create: Prisma.XOR<Prisma.RoutingStepCreateInput, Prisma.RoutingStepUncheckedCreateInput>
  /**
   * In case the RoutingStep was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RoutingStepUpdateInput, Prisma.RoutingStepUncheckedUpdateInput>
}

/**
 * RoutingStep delete
 */
export type RoutingStepDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
  /**
   * Filter which RoutingStep to delete.
   */
  where: Prisma.RoutingStepWhereUniqueInput
}

/**
 * RoutingStep deleteMany
 */
export type RoutingStepDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoutingSteps to delete
   */
  where?: Prisma.RoutingStepWhereInput
  /**
   * Limit how many RoutingSteps to delete.
   */
  limit?: number
}

/**
 * RoutingStep.operations
 */
export type RoutingStep$operationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Operation
   */
  select?: Prisma.OperationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Operation
   */
  omit?: Prisma.OperationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OperationInclude<ExtArgs> | null
  where?: Prisma.OperationWhereInput
  orderBy?: Prisma.OperationOrderByWithRelationInput | Prisma.OperationOrderByWithRelationInput[]
  cursor?: Prisma.OperationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OperationScalarFieldEnum | Prisma.OperationScalarFieldEnum[]
}

/**
 * RoutingStep.defaultMachine
 */
export type RoutingStep$defaultMachineArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Machine
   */
  select?: Prisma.MachineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Machine
   */
  omit?: Prisma.MachineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MachineInclude<ExtArgs> | null
  where?: Prisma.MachineWhereInput
}

/**
 * RoutingStep without action
 */
export type RoutingStepDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoutingStep
   */
  select?: Prisma.RoutingStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoutingStep
   */
  omit?: Prisma.RoutingStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoutingStepInclude<ExtArgs> | null
}
