
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StockLedger` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model StockLedger
 * 
 */
export type StockLedgerModel = runtime.Types.Result.DefaultSelection<Prisma.$StockLedgerPayload>

export type AggregateStockLedger = {
  _count: StockLedgerCountAggregateOutputType | null
  _avg: StockLedgerAvgAggregateOutputType | null
  _sum: StockLedgerSumAggregateOutputType | null
  _min: StockLedgerMinAggregateOutputType | null
  _max: StockLedgerMaxAggregateOutputType | null
}

export type StockLedgerAvgAggregateOutputType = {
  qtyChange: runtime.Decimal | null
  balanceAfter: runtime.Decimal | null
}

export type StockLedgerSumAggregateOutputType = {
  qtyChange: runtime.Decimal | null
  balanceAfter: runtime.Decimal | null
}

export type StockLedgerMinAggregateOutputType = {
  id: string | null
  materialId: string | null
  transactionType: $Enums.LedgerTransactionType | null
  qtyChange: runtime.Decimal | null
  balanceAfter: runtime.Decimal | null
  reason: string | null
  referenceId: string | null
  userId: string | null
  createdAt: Date | null
}

export type StockLedgerMaxAggregateOutputType = {
  id: string | null
  materialId: string | null
  transactionType: $Enums.LedgerTransactionType | null
  qtyChange: runtime.Decimal | null
  balanceAfter: runtime.Decimal | null
  reason: string | null
  referenceId: string | null
  userId: string | null
  createdAt: Date | null
}

export type StockLedgerCountAggregateOutputType = {
  id: number
  materialId: number
  transactionType: number
  qtyChange: number
  balanceAfter: number
  reason: number
  referenceId: number
  userId: number
  createdAt: number
  _all: number
}


export type StockLedgerAvgAggregateInputType = {
  qtyChange?: true
  balanceAfter?: true
}

export type StockLedgerSumAggregateInputType = {
  qtyChange?: true
  balanceAfter?: true
}

export type StockLedgerMinAggregateInputType = {
  id?: true
  materialId?: true
  transactionType?: true
  qtyChange?: true
  balanceAfter?: true
  reason?: true
  referenceId?: true
  userId?: true
  createdAt?: true
}

export type StockLedgerMaxAggregateInputType = {
  id?: true
  materialId?: true
  transactionType?: true
  qtyChange?: true
  balanceAfter?: true
  reason?: true
  referenceId?: true
  userId?: true
  createdAt?: true
}

export type StockLedgerCountAggregateInputType = {
  id?: true
  materialId?: true
  transactionType?: true
  qtyChange?: true
  balanceAfter?: true
  reason?: true
  referenceId?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type StockLedgerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StockLedger to aggregate.
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockLedgers to fetch.
   */
  orderBy?: Prisma.StockLedgerOrderByWithRelationInput | Prisma.StockLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StockLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StockLedgers
  **/
  _count?: true | StockLedgerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StockLedgerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StockLedgerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StockLedgerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StockLedgerMaxAggregateInputType
}

export type GetStockLedgerAggregateType<T extends StockLedgerAggregateArgs> = {
      [P in keyof T & keyof AggregateStockLedger]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStockLedger[P]>
    : Prisma.GetScalarType<T[P], AggregateStockLedger[P]>
}




export type StockLedgerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StockLedgerWhereInput
  orderBy?: Prisma.StockLedgerOrderByWithAggregationInput | Prisma.StockLedgerOrderByWithAggregationInput[]
  by: Prisma.StockLedgerScalarFieldEnum[] | Prisma.StockLedgerScalarFieldEnum
  having?: Prisma.StockLedgerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StockLedgerCountAggregateInputType | true
  _avg?: StockLedgerAvgAggregateInputType
  _sum?: StockLedgerSumAggregateInputType
  _min?: StockLedgerMinAggregateInputType
  _max?: StockLedgerMaxAggregateInputType
}

export type StockLedgerGroupByOutputType = {
  id: string
  materialId: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal
  balanceAfter: runtime.Decimal
  reason: string | null
  referenceId: string | null
  userId: string | null
  createdAt: Date
  _count: StockLedgerCountAggregateOutputType | null
  _avg: StockLedgerAvgAggregateOutputType | null
  _sum: StockLedgerSumAggregateOutputType | null
  _min: StockLedgerMinAggregateOutputType | null
  _max: StockLedgerMaxAggregateOutputType | null
}

export type GetStockLedgerGroupByPayload<T extends StockLedgerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StockLedgerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StockLedgerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StockLedgerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StockLedgerGroupByOutputType[P]>
      }
    >
  >



export type StockLedgerWhereInput = {
  AND?: Prisma.StockLedgerWhereInput | Prisma.StockLedgerWhereInput[]
  OR?: Prisma.StockLedgerWhereInput[]
  NOT?: Prisma.StockLedgerWhereInput | Prisma.StockLedgerWhereInput[]
  id?: Prisma.StringFilter<"StockLedger"> | string
  materialId?: Prisma.StringFilter<"StockLedger"> | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFilter<"StockLedger"> | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  referenceId?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  userId?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StockLedger"> | Date | string
  material?: Prisma.XOR<Prisma.MaterialScalarRelationFilter, Prisma.MaterialWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type StockLedgerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  transactionType?: Prisma.SortOrder
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  referenceId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  material?: Prisma.MaterialOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type StockLedgerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StockLedgerWhereInput | Prisma.StockLedgerWhereInput[]
  OR?: Prisma.StockLedgerWhereInput[]
  NOT?: Prisma.StockLedgerWhereInput | Prisma.StockLedgerWhereInput[]
  materialId?: Prisma.StringFilter<"StockLedger"> | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFilter<"StockLedger"> | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  referenceId?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  userId?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StockLedger"> | Date | string
  material?: Prisma.XOR<Prisma.MaterialScalarRelationFilter, Prisma.MaterialWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type StockLedgerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  transactionType?: Prisma.SortOrder
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  referenceId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.StockLedgerCountOrderByAggregateInput
  _avg?: Prisma.StockLedgerAvgOrderByAggregateInput
  _max?: Prisma.StockLedgerMaxOrderByAggregateInput
  _min?: Prisma.StockLedgerMinOrderByAggregateInput
  _sum?: Prisma.StockLedgerSumOrderByAggregateInput
}

export type StockLedgerScalarWhereWithAggregatesInput = {
  AND?: Prisma.StockLedgerScalarWhereWithAggregatesInput | Prisma.StockLedgerScalarWhereWithAggregatesInput[]
  OR?: Prisma.StockLedgerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StockLedgerScalarWhereWithAggregatesInput | Prisma.StockLedgerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StockLedger"> | string
  materialId?: Prisma.StringWithAggregatesFilter<"StockLedger"> | string
  transactionType?: Prisma.EnumLedgerTransactionTypeWithAggregatesFilter<"StockLedger"> | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalWithAggregatesFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalWithAggregatesFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.StringNullableWithAggregatesFilter<"StockLedger"> | string | null
  referenceId?: Prisma.StringNullableWithAggregatesFilter<"StockLedger"> | string | null
  userId?: Prisma.StringNullableWithAggregatesFilter<"StockLedger"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StockLedger"> | Date | string
}

export type StockLedgerCreateInput = {
  id?: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  createdAt?: Date | string
  material: Prisma.MaterialCreateNestedOneWithoutStockLedgersInput
  user?: Prisma.UserCreateNestedOneWithoutStockLedgersInput
}

export type StockLedgerUncheckedCreateInput = {
  id?: string
  materialId: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  userId?: string | null
  createdAt?: Date | string
}

export type StockLedgerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  material?: Prisma.MaterialUpdateOneRequiredWithoutStockLedgersNestedInput
  user?: Prisma.UserUpdateOneWithoutStockLedgersNestedInput
}

export type StockLedgerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockLedgerCreateManyInput = {
  id?: string
  materialId: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  userId?: string | null
  createdAt?: Date | string
}

export type StockLedgerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockLedgerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockLedgerListRelationFilter = {
  every?: Prisma.StockLedgerWhereInput
  some?: Prisma.StockLedgerWhereInput
  none?: Prisma.StockLedgerWhereInput
}

export type StockLedgerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StockLedgerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  transactionType?: Prisma.SortOrder
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  referenceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StockLedgerAvgOrderByAggregateInput = {
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
}

export type StockLedgerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  transactionType?: Prisma.SortOrder
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  referenceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StockLedgerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  transactionType?: Prisma.SortOrder
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  referenceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type StockLedgerSumOrderByAggregateInput = {
  qtyChange?: Prisma.SortOrder
  balanceAfter?: Prisma.SortOrder
}

export type StockLedgerCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutUserInput, Prisma.StockLedgerUncheckedCreateWithoutUserInput> | Prisma.StockLedgerCreateWithoutUserInput[] | Prisma.StockLedgerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutUserInput | Prisma.StockLedgerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StockLedgerCreateManyUserInputEnvelope
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
}

export type StockLedgerUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutUserInput, Prisma.StockLedgerUncheckedCreateWithoutUserInput> | Prisma.StockLedgerCreateWithoutUserInput[] | Prisma.StockLedgerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutUserInput | Prisma.StockLedgerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StockLedgerCreateManyUserInputEnvelope
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
}

export type StockLedgerUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutUserInput, Prisma.StockLedgerUncheckedCreateWithoutUserInput> | Prisma.StockLedgerCreateWithoutUserInput[] | Prisma.StockLedgerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutUserInput | Prisma.StockLedgerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StockLedgerUpsertWithWhereUniqueWithoutUserInput | Prisma.StockLedgerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StockLedgerCreateManyUserInputEnvelope
  set?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  disconnect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  delete?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  update?: Prisma.StockLedgerUpdateWithWhereUniqueWithoutUserInput | Prisma.StockLedgerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StockLedgerUpdateManyWithWhereWithoutUserInput | Prisma.StockLedgerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StockLedgerScalarWhereInput | Prisma.StockLedgerScalarWhereInput[]
}

export type StockLedgerUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutUserInput, Prisma.StockLedgerUncheckedCreateWithoutUserInput> | Prisma.StockLedgerCreateWithoutUserInput[] | Prisma.StockLedgerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutUserInput | Prisma.StockLedgerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StockLedgerUpsertWithWhereUniqueWithoutUserInput | Prisma.StockLedgerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StockLedgerCreateManyUserInputEnvelope
  set?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  disconnect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  delete?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  update?: Prisma.StockLedgerUpdateWithWhereUniqueWithoutUserInput | Prisma.StockLedgerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StockLedgerUpdateManyWithWhereWithoutUserInput | Prisma.StockLedgerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StockLedgerScalarWhereInput | Prisma.StockLedgerScalarWhereInput[]
}

export type StockLedgerCreateNestedManyWithoutMaterialInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutMaterialInput, Prisma.StockLedgerUncheckedCreateWithoutMaterialInput> | Prisma.StockLedgerCreateWithoutMaterialInput[] | Prisma.StockLedgerUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutMaterialInput | Prisma.StockLedgerCreateOrConnectWithoutMaterialInput[]
  createMany?: Prisma.StockLedgerCreateManyMaterialInputEnvelope
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
}

export type StockLedgerUncheckedCreateNestedManyWithoutMaterialInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutMaterialInput, Prisma.StockLedgerUncheckedCreateWithoutMaterialInput> | Prisma.StockLedgerCreateWithoutMaterialInput[] | Prisma.StockLedgerUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutMaterialInput | Prisma.StockLedgerCreateOrConnectWithoutMaterialInput[]
  createMany?: Prisma.StockLedgerCreateManyMaterialInputEnvelope
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
}

export type StockLedgerUpdateManyWithoutMaterialNestedInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutMaterialInput, Prisma.StockLedgerUncheckedCreateWithoutMaterialInput> | Prisma.StockLedgerCreateWithoutMaterialInput[] | Prisma.StockLedgerUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutMaterialInput | Prisma.StockLedgerCreateOrConnectWithoutMaterialInput[]
  upsert?: Prisma.StockLedgerUpsertWithWhereUniqueWithoutMaterialInput | Prisma.StockLedgerUpsertWithWhereUniqueWithoutMaterialInput[]
  createMany?: Prisma.StockLedgerCreateManyMaterialInputEnvelope
  set?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  disconnect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  delete?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  update?: Prisma.StockLedgerUpdateWithWhereUniqueWithoutMaterialInput | Prisma.StockLedgerUpdateWithWhereUniqueWithoutMaterialInput[]
  updateMany?: Prisma.StockLedgerUpdateManyWithWhereWithoutMaterialInput | Prisma.StockLedgerUpdateManyWithWhereWithoutMaterialInput[]
  deleteMany?: Prisma.StockLedgerScalarWhereInput | Prisma.StockLedgerScalarWhereInput[]
}

export type StockLedgerUncheckedUpdateManyWithoutMaterialNestedInput = {
  create?: Prisma.XOR<Prisma.StockLedgerCreateWithoutMaterialInput, Prisma.StockLedgerUncheckedCreateWithoutMaterialInput> | Prisma.StockLedgerCreateWithoutMaterialInput[] | Prisma.StockLedgerUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.StockLedgerCreateOrConnectWithoutMaterialInput | Prisma.StockLedgerCreateOrConnectWithoutMaterialInput[]
  upsert?: Prisma.StockLedgerUpsertWithWhereUniqueWithoutMaterialInput | Prisma.StockLedgerUpsertWithWhereUniqueWithoutMaterialInput[]
  createMany?: Prisma.StockLedgerCreateManyMaterialInputEnvelope
  set?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  disconnect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  delete?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  connect?: Prisma.StockLedgerWhereUniqueInput | Prisma.StockLedgerWhereUniqueInput[]
  update?: Prisma.StockLedgerUpdateWithWhereUniqueWithoutMaterialInput | Prisma.StockLedgerUpdateWithWhereUniqueWithoutMaterialInput[]
  updateMany?: Prisma.StockLedgerUpdateManyWithWhereWithoutMaterialInput | Prisma.StockLedgerUpdateManyWithWhereWithoutMaterialInput[]
  deleteMany?: Prisma.StockLedgerScalarWhereInput | Prisma.StockLedgerScalarWhereInput[]
}

export type EnumLedgerTransactionTypeFieldUpdateOperationsInput = {
  set?: $Enums.LedgerTransactionType
}

export type StockLedgerCreateWithoutUserInput = {
  id?: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  createdAt?: Date | string
  material: Prisma.MaterialCreateNestedOneWithoutStockLedgersInput
}

export type StockLedgerUncheckedCreateWithoutUserInput = {
  id?: string
  materialId: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  createdAt?: Date | string
}

export type StockLedgerCreateOrConnectWithoutUserInput = {
  where: Prisma.StockLedgerWhereUniqueInput
  create: Prisma.XOR<Prisma.StockLedgerCreateWithoutUserInput, Prisma.StockLedgerUncheckedCreateWithoutUserInput>
}

export type StockLedgerCreateManyUserInputEnvelope = {
  data: Prisma.StockLedgerCreateManyUserInput | Prisma.StockLedgerCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StockLedgerUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StockLedgerWhereUniqueInput
  update: Prisma.XOR<Prisma.StockLedgerUpdateWithoutUserInput, Prisma.StockLedgerUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StockLedgerCreateWithoutUserInput, Prisma.StockLedgerUncheckedCreateWithoutUserInput>
}

export type StockLedgerUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StockLedgerWhereUniqueInput
  data: Prisma.XOR<Prisma.StockLedgerUpdateWithoutUserInput, Prisma.StockLedgerUncheckedUpdateWithoutUserInput>
}

export type StockLedgerUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StockLedgerScalarWhereInput
  data: Prisma.XOR<Prisma.StockLedgerUpdateManyMutationInput, Prisma.StockLedgerUncheckedUpdateManyWithoutUserInput>
}

export type StockLedgerScalarWhereInput = {
  AND?: Prisma.StockLedgerScalarWhereInput | Prisma.StockLedgerScalarWhereInput[]
  OR?: Prisma.StockLedgerScalarWhereInput[]
  NOT?: Prisma.StockLedgerScalarWhereInput | Prisma.StockLedgerScalarWhereInput[]
  id?: Prisma.StringFilter<"StockLedger"> | string
  materialId?: Prisma.StringFilter<"StockLedger"> | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFilter<"StockLedger"> | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFilter<"StockLedger"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  referenceId?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  userId?: Prisma.StringNullableFilter<"StockLedger"> | string | null
  createdAt?: Prisma.DateTimeFilter<"StockLedger"> | Date | string
}

export type StockLedgerCreateWithoutMaterialInput = {
  id?: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutStockLedgersInput
}

export type StockLedgerUncheckedCreateWithoutMaterialInput = {
  id?: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  userId?: string | null
  createdAt?: Date | string
}

export type StockLedgerCreateOrConnectWithoutMaterialInput = {
  where: Prisma.StockLedgerWhereUniqueInput
  create: Prisma.XOR<Prisma.StockLedgerCreateWithoutMaterialInput, Prisma.StockLedgerUncheckedCreateWithoutMaterialInput>
}

export type StockLedgerCreateManyMaterialInputEnvelope = {
  data: Prisma.StockLedgerCreateManyMaterialInput | Prisma.StockLedgerCreateManyMaterialInput[]
  skipDuplicates?: boolean
}

export type StockLedgerUpsertWithWhereUniqueWithoutMaterialInput = {
  where: Prisma.StockLedgerWhereUniqueInput
  update: Prisma.XOR<Prisma.StockLedgerUpdateWithoutMaterialInput, Prisma.StockLedgerUncheckedUpdateWithoutMaterialInput>
  create: Prisma.XOR<Prisma.StockLedgerCreateWithoutMaterialInput, Prisma.StockLedgerUncheckedCreateWithoutMaterialInput>
}

export type StockLedgerUpdateWithWhereUniqueWithoutMaterialInput = {
  where: Prisma.StockLedgerWhereUniqueInput
  data: Prisma.XOR<Prisma.StockLedgerUpdateWithoutMaterialInput, Prisma.StockLedgerUncheckedUpdateWithoutMaterialInput>
}

export type StockLedgerUpdateManyWithWhereWithoutMaterialInput = {
  where: Prisma.StockLedgerScalarWhereInput
  data: Prisma.XOR<Prisma.StockLedgerUpdateManyMutationInput, Prisma.StockLedgerUncheckedUpdateManyWithoutMaterialInput>
}

export type StockLedgerCreateManyUserInput = {
  id?: string
  materialId: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  createdAt?: Date | string
}

export type StockLedgerUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  material?: Prisma.MaterialUpdateOneRequiredWithoutStockLedgersNestedInput
}

export type StockLedgerUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockLedgerUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  materialId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockLedgerCreateManyMaterialInput = {
  id?: string
  transactionType: $Enums.LedgerTransactionType
  qtyChange: runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter: runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: string | null
  referenceId?: string | null
  userId?: string | null
  createdAt?: Date | string
}

export type StockLedgerUpdateWithoutMaterialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutStockLedgersNestedInput
}

export type StockLedgerUncheckedUpdateWithoutMaterialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockLedgerUncheckedUpdateManyWithoutMaterialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionType?: Prisma.EnumLedgerTransactionTypeFieldUpdateOperationsInput | $Enums.LedgerTransactionType
  qtyChange?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  balanceAfter?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StockLedgerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  materialId?: boolean
  transactionType?: boolean
  qtyChange?: boolean
  balanceAfter?: boolean
  reason?: boolean
  referenceId?: boolean
  userId?: boolean
  createdAt?: boolean
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockLedger$userArgs<ExtArgs>
}, ExtArgs["result"]["stockLedger"]>

export type StockLedgerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  materialId?: boolean
  transactionType?: boolean
  qtyChange?: boolean
  balanceAfter?: boolean
  reason?: boolean
  referenceId?: boolean
  userId?: boolean
  createdAt?: boolean
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockLedger$userArgs<ExtArgs>
}, ExtArgs["result"]["stockLedger"]>

export type StockLedgerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  materialId?: boolean
  transactionType?: boolean
  qtyChange?: boolean
  balanceAfter?: boolean
  reason?: boolean
  referenceId?: boolean
  userId?: boolean
  createdAt?: boolean
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockLedger$userArgs<ExtArgs>
}, ExtArgs["result"]["stockLedger"]>

export type StockLedgerSelectScalar = {
  id?: boolean
  materialId?: boolean
  transactionType?: boolean
  qtyChange?: boolean
  balanceAfter?: boolean
  reason?: boolean
  referenceId?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type StockLedgerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "materialId" | "transactionType" | "qtyChange" | "balanceAfter" | "reason" | "referenceId" | "userId" | "createdAt", ExtArgs["result"]["stockLedger"]>
export type StockLedgerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockLedger$userArgs<ExtArgs>
}
export type StockLedgerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockLedger$userArgs<ExtArgs>
}
export type StockLedgerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  material?: boolean | Prisma.MaterialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.StockLedger$userArgs<ExtArgs>
}

export type $StockLedgerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StockLedger"
  objects: {
    material: Prisma.$MaterialPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    materialId: string
    transactionType: $Enums.LedgerTransactionType
    qtyChange: runtime.Decimal
    balanceAfter: runtime.Decimal
    reason: string | null
    referenceId: string | null
    userId: string | null
    createdAt: Date
  }, ExtArgs["result"]["stockLedger"]>
  composites: {}
}

export type StockLedgerGetPayload<S extends boolean | null | undefined | StockLedgerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload, S>

export type StockLedgerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StockLedgerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StockLedgerCountAggregateInputType | true
  }

export interface StockLedgerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StockLedger'], meta: { name: 'StockLedger' } }
  /**
   * Find zero or one StockLedger that matches the filter.
   * @param {StockLedgerFindUniqueArgs} args - Arguments to find a StockLedger
   * @example
   * // Get one StockLedger
   * const stockLedger = await prisma.stockLedger.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StockLedgerFindUniqueArgs>(args: Prisma.SelectSubset<T, StockLedgerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StockLedger that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StockLedgerFindUniqueOrThrowArgs} args - Arguments to find a StockLedger
   * @example
   * // Get one StockLedger
   * const stockLedger = await prisma.stockLedger.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StockLedgerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StockLedgerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StockLedger that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerFindFirstArgs} args - Arguments to find a StockLedger
   * @example
   * // Get one StockLedger
   * const stockLedger = await prisma.stockLedger.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StockLedgerFindFirstArgs>(args?: Prisma.SelectSubset<T, StockLedgerFindFirstArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StockLedger that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerFindFirstOrThrowArgs} args - Arguments to find a StockLedger
   * @example
   * // Get one StockLedger
   * const stockLedger = await prisma.stockLedger.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StockLedgerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StockLedgerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StockLedgers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StockLedgers
   * const stockLedgers = await prisma.stockLedger.findMany()
   * 
   * // Get first 10 StockLedgers
   * const stockLedgers = await prisma.stockLedger.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stockLedgerWithIdOnly = await prisma.stockLedger.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StockLedgerFindManyArgs>(args?: Prisma.SelectSubset<T, StockLedgerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StockLedger.
   * @param {StockLedgerCreateArgs} args - Arguments to create a StockLedger.
   * @example
   * // Create one StockLedger
   * const StockLedger = await prisma.stockLedger.create({
   *   data: {
   *     // ... data to create a StockLedger
   *   }
   * })
   * 
   */
  create<T extends StockLedgerCreateArgs>(args: Prisma.SelectSubset<T, StockLedgerCreateArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StockLedgers.
   * @param {StockLedgerCreateManyArgs} args - Arguments to create many StockLedgers.
   * @example
   * // Create many StockLedgers
   * const stockLedger = await prisma.stockLedger.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StockLedgerCreateManyArgs>(args?: Prisma.SelectSubset<T, StockLedgerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StockLedgers and returns the data saved in the database.
   * @param {StockLedgerCreateManyAndReturnArgs} args - Arguments to create many StockLedgers.
   * @example
   * // Create many StockLedgers
   * const stockLedger = await prisma.stockLedger.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StockLedgers and only return the `id`
   * const stockLedgerWithIdOnly = await prisma.stockLedger.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StockLedgerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StockLedgerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StockLedger.
   * @param {StockLedgerDeleteArgs} args - Arguments to delete one StockLedger.
   * @example
   * // Delete one StockLedger
   * const StockLedger = await prisma.stockLedger.delete({
   *   where: {
   *     // ... filter to delete one StockLedger
   *   }
   * })
   * 
   */
  delete<T extends StockLedgerDeleteArgs>(args: Prisma.SelectSubset<T, StockLedgerDeleteArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StockLedger.
   * @param {StockLedgerUpdateArgs} args - Arguments to update one StockLedger.
   * @example
   * // Update one StockLedger
   * const stockLedger = await prisma.stockLedger.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StockLedgerUpdateArgs>(args: Prisma.SelectSubset<T, StockLedgerUpdateArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StockLedgers.
   * @param {StockLedgerDeleteManyArgs} args - Arguments to filter StockLedgers to delete.
   * @example
   * // Delete a few StockLedgers
   * const { count } = await prisma.stockLedger.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StockLedgerDeleteManyArgs>(args?: Prisma.SelectSubset<T, StockLedgerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StockLedgers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StockLedgers
   * const stockLedger = await prisma.stockLedger.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StockLedgerUpdateManyArgs>(args: Prisma.SelectSubset<T, StockLedgerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StockLedgers and returns the data updated in the database.
   * @param {StockLedgerUpdateManyAndReturnArgs} args - Arguments to update many StockLedgers.
   * @example
   * // Update many StockLedgers
   * const stockLedger = await prisma.stockLedger.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StockLedgers and only return the `id`
   * const stockLedgerWithIdOnly = await prisma.stockLedger.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StockLedgerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StockLedgerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StockLedger.
   * @param {StockLedgerUpsertArgs} args - Arguments to update or create a StockLedger.
   * @example
   * // Update or create a StockLedger
   * const stockLedger = await prisma.stockLedger.upsert({
   *   create: {
   *     // ... data to create a StockLedger
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StockLedger we want to update
   *   }
   * })
   */
  upsert<T extends StockLedgerUpsertArgs>(args: Prisma.SelectSubset<T, StockLedgerUpsertArgs<ExtArgs>>): Prisma.Prisma__StockLedgerClient<runtime.Types.Result.GetResult<Prisma.$StockLedgerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StockLedgers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerCountArgs} args - Arguments to filter StockLedgers to count.
   * @example
   * // Count the number of StockLedgers
   * const count = await prisma.stockLedger.count({
   *   where: {
   *     // ... the filter for the StockLedgers we want to count
   *   }
   * })
  **/
  count<T extends StockLedgerCountArgs>(
    args?: Prisma.Subset<T, StockLedgerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StockLedgerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StockLedger.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StockLedgerAggregateArgs>(args: Prisma.Subset<T, StockLedgerAggregateArgs>): Prisma.PrismaPromise<GetStockLedgerAggregateType<T>>

  /**
   * Group by StockLedger.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockLedgerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StockLedgerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StockLedgerGroupByArgs['orderBy'] }
      : { orderBy?: StockLedgerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StockLedgerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStockLedgerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StockLedger model
 */
readonly fields: StockLedgerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StockLedger.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StockLedgerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  material<T extends Prisma.MaterialDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MaterialDefaultArgs<ExtArgs>>): Prisma.Prisma__MaterialClient<runtime.Types.Result.GetResult<Prisma.$MaterialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.StockLedger$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StockLedger$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StockLedger model
 */
export interface StockLedgerFieldRefs {
  readonly id: Prisma.FieldRef<"StockLedger", 'String'>
  readonly materialId: Prisma.FieldRef<"StockLedger", 'String'>
  readonly transactionType: Prisma.FieldRef<"StockLedger", 'LedgerTransactionType'>
  readonly qtyChange: Prisma.FieldRef<"StockLedger", 'Decimal'>
  readonly balanceAfter: Prisma.FieldRef<"StockLedger", 'Decimal'>
  readonly reason: Prisma.FieldRef<"StockLedger", 'String'>
  readonly referenceId: Prisma.FieldRef<"StockLedger", 'String'>
  readonly userId: Prisma.FieldRef<"StockLedger", 'String'>
  readonly createdAt: Prisma.FieldRef<"StockLedger", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StockLedger findUnique
 */
export type StockLedgerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * Filter, which StockLedger to fetch.
   */
  where: Prisma.StockLedgerWhereUniqueInput
}

/**
 * StockLedger findUniqueOrThrow
 */
export type StockLedgerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * Filter, which StockLedger to fetch.
   */
  where: Prisma.StockLedgerWhereUniqueInput
}

/**
 * StockLedger findFirst
 */
export type StockLedgerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * Filter, which StockLedger to fetch.
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockLedgers to fetch.
   */
  orderBy?: Prisma.StockLedgerOrderByWithRelationInput | Prisma.StockLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StockLedgers.
   */
  cursor?: Prisma.StockLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockLedgers.
   */
  distinct?: Prisma.StockLedgerScalarFieldEnum | Prisma.StockLedgerScalarFieldEnum[]
}

/**
 * StockLedger findFirstOrThrow
 */
export type StockLedgerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * Filter, which StockLedger to fetch.
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockLedgers to fetch.
   */
  orderBy?: Prisma.StockLedgerOrderByWithRelationInput | Prisma.StockLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StockLedgers.
   */
  cursor?: Prisma.StockLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockLedgers.
   */
  distinct?: Prisma.StockLedgerScalarFieldEnum | Prisma.StockLedgerScalarFieldEnum[]
}

/**
 * StockLedger findMany
 */
export type StockLedgerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * Filter, which StockLedgers to fetch.
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockLedgers to fetch.
   */
  orderBy?: Prisma.StockLedgerOrderByWithRelationInput | Prisma.StockLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StockLedgers.
   */
  cursor?: Prisma.StockLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockLedgers.
   */
  distinct?: Prisma.StockLedgerScalarFieldEnum | Prisma.StockLedgerScalarFieldEnum[]
}

/**
 * StockLedger create
 */
export type StockLedgerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * The data needed to create a StockLedger.
   */
  data: Prisma.XOR<Prisma.StockLedgerCreateInput, Prisma.StockLedgerUncheckedCreateInput>
}

/**
 * StockLedger createMany
 */
export type StockLedgerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StockLedgers.
   */
  data: Prisma.StockLedgerCreateManyInput | Prisma.StockLedgerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StockLedger createManyAndReturn
 */
export type StockLedgerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * The data used to create many StockLedgers.
   */
  data: Prisma.StockLedgerCreateManyInput | Prisma.StockLedgerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StockLedger update
 */
export type StockLedgerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * The data needed to update a StockLedger.
   */
  data: Prisma.XOR<Prisma.StockLedgerUpdateInput, Prisma.StockLedgerUncheckedUpdateInput>
  /**
   * Choose, which StockLedger to update.
   */
  where: Prisma.StockLedgerWhereUniqueInput
}

/**
 * StockLedger updateMany
 */
export type StockLedgerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StockLedgers.
   */
  data: Prisma.XOR<Prisma.StockLedgerUpdateManyMutationInput, Prisma.StockLedgerUncheckedUpdateManyInput>
  /**
   * Filter which StockLedgers to update
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * Limit how many StockLedgers to update.
   */
  limit?: number
}

/**
 * StockLedger updateManyAndReturn
 */
export type StockLedgerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * The data used to update StockLedgers.
   */
  data: Prisma.XOR<Prisma.StockLedgerUpdateManyMutationInput, Prisma.StockLedgerUncheckedUpdateManyInput>
  /**
   * Filter which StockLedgers to update
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * Limit how many StockLedgers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StockLedger upsert
 */
export type StockLedgerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * The filter to search for the StockLedger to update in case it exists.
   */
  where: Prisma.StockLedgerWhereUniqueInput
  /**
   * In case the StockLedger found by the `where` argument doesn't exist, create a new StockLedger with this data.
   */
  create: Prisma.XOR<Prisma.StockLedgerCreateInput, Prisma.StockLedgerUncheckedCreateInput>
  /**
   * In case the StockLedger was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StockLedgerUpdateInput, Prisma.StockLedgerUncheckedUpdateInput>
}

/**
 * StockLedger delete
 */
export type StockLedgerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
  /**
   * Filter which StockLedger to delete.
   */
  where: Prisma.StockLedgerWhereUniqueInput
}

/**
 * StockLedger deleteMany
 */
export type StockLedgerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StockLedgers to delete
   */
  where?: Prisma.StockLedgerWhereInput
  /**
   * Limit how many StockLedgers to delete.
   */
  limit?: number
}

/**
 * StockLedger.user
 */
export type StockLedger$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * StockLedger without action
 */
export type StockLedgerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockLedger
   */
  select?: Prisma.StockLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockLedger
   */
  omit?: Prisma.StockLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockLedgerInclude<ExtArgs> | null
}
